#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
// 由 openapi/*.yaml 生成 sdk/src/*.gen.ts。
//   pnpm gen          重新生成
//   pnpm gen:check    只检查生成结果是否最新（CI 使用），不一致时退出码为 1
// 生成前校验 openapi/ 中的拷贝与 lock.json 记录的 SHA-256 一致，防止手改拷贝。
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const webDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const lock = JSON.parse(readFileSync(join(webDir, 'openapi', 'lock.json'), 'utf8'));

const targets = [
  { spec: 'client.v1.yaml', out: 'sdk/src/client.gen.ts' },
  { spec: 'console.v1.yaml', out: 'sdk/src/console.gen.ts' },
];

let stale = false;
for (const { spec, out } of targets) {
  const specPath = join(webDir, 'openapi', spec);
  const text = readFileSync(specPath, 'utf8');
  const sum = createHash('sha256').update(text).digest('hex');
  if (sum !== lock.files[spec]) {
    console.error(`${spec} 与 lock.json 不一致：不要手改拷贝，用 pnpm sync-openapi 更新`);
    process.exit(1);
  }
  const ast = await openapiTS(pathToFileURL(specPath), { alphabetize: false });
  const body = [
    // 拆开拼接，避免 REUSE 把这行字面量当成本文件的许可证标签。
    '// SPDX' + '-License-Identifier: AGPL-3.0-or-later',
    `// Code generated by pnpm gen from panel-spec ${lock.ref} (${spec}). DO NOT EDIT.`,
    '',
    astToString(ast),
  ].join('\n');
  const outPath = join(webDir, out);
  const current = existsSync(outPath) ? readFileSync(outPath, 'utf8') : '';
  if (current === body) continue;
  if (check) {
    console.error(`${out} 不是最新，请运行 pnpm gen`);
    stale = true;
  } else {
    writeFileSync(outPath, body);
    console.log(`生成 ${out}`);
  }
}
process.exit(stale ? 1 : 0);
