#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
// 由 openapi/*.yaml 生成 sdk/src/*.gen.ts。
//   pnpm gen          重新生成
//   pnpm gen:check    只检查生成结果是否最新（CI 使用），不一致时退出码为 1
// 管理接口另外生成 sdk/src/console.ops.gen.ts：每个操作的 x-permission 与 x-sensitive（AUTH-17、AUTH-19），
// 供管理后台决定菜单、按钮与二次确认；openapi-typescript 不保留这两个扩展字段。
// 生成前校验 openapi/ 中的拷贝与 lock.json 记录的 SHA-256 一致，防止手改拷贝。
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import { parse } from 'yaml';

const webDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const lock = JSON.parse(readFileSync(join(webDir, 'openapi', 'lock.json'), 'utf8'));

const targets = [
  { spec: 'client.v1.yaml', out: 'sdk/src/client.gen.ts' },
  { spec: 'console.v1.yaml', out: 'sdk/src/console.gen.ts', ops: 'sdk/src/console.ops.gen.ts' },
];

const methods = ['get', 'put', 'post', 'delete', 'patch'];

/** 按“方法 路径”列出每个操作的 x-permission 与 x-sensitive。缺少 x-permission 时报错（CON-02）。 */
function operationsModule(specText, spec) {
  const doc = parse(specText);
  const lines = [];
  for (const [path, item] of Object.entries(doc.paths ?? {})) {
    for (const m of methods) {
      const op = item?.[m];
      if (!op) continue;
      const permission = op['x-permission'];
      if (typeof permission !== 'string') {
        console.error(`${spec}: ${m.toUpperCase()} ${path} 缺少 x-permission`);
        process.exit(1);
      }
      const sensitive = op['x-sensitive'] === true;
      lines.push(`  ${JSON.stringify(`${m.toUpperCase()} ${path}`)}: { permission: ${JSON.stringify(permission)}, sensitive: ${sensitive} },`);
    }
  }
  return ['export const consoleOperations = {', ...lines, '} as const;', ''].join('\n');
}

function header(spec) {
  return [
    // 拆开拼接，避免 REUSE 把这行字面量当成本文件的许可证标签。
    '// SPDX' + '-License-Identifier: AGPL-3.0-or-later',
    `// Code generated by pnpm gen from panel-spec ${lock.ref} (${spec}). DO NOT EDIT.`,
    '',
  ];
}

function emit(out, body) {
  const outPath = join(webDir, out);
  const current = existsSync(outPath) ? readFileSync(outPath, 'utf8') : '';
  if (current === body) return;
  if (check) {
    console.error(`${out} 不是最新，请运行 pnpm gen`);
    stale = true;
  } else {
    writeFileSync(outPath, body);
    console.log(`生成 ${out}`);
  }
}

let stale = false;
for (const { spec, out, ops } of targets) {
  const specPath = join(webDir, 'openapi', spec);
  const text = readFileSync(specPath, 'utf8');
  const sum = createHash('sha256').update(text).digest('hex');
  if (sum !== lock.files[spec]) {
    console.error(`${spec} 与 lock.json 不一致：不要手改拷贝，用 pnpm sync-openapi 更新`);
    process.exit(1);
  }
  const ast = await openapiTS(pathToFileURL(specPath), { alphabetize: false });
  emit(out, [...header(spec), astToString(ast)].join('\n'));
  if (ops) emit(ops, [...header(spec), operationsModule(text, spec)].join('\n'));
}
process.exit(stale ? 1 : 0);
