// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const accountByEmail = `-- name: AccountByEmail :one

SELECT id, email, password_hash, status, email_verified_at, locale
FROM accounts WHERE lower(email) = lower($1::text)
`

type AccountByEmailRow struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    *string
	Status          string
	EmailVerifiedAt *time.Time
	Locale          string
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// 账号、注册与验证码（spec/10 AUTH-01–04）。
func (q *Queries) AccountByEmail(ctx context.Context, email string) (AccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, accountByEmail, email)
	var i AccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.Locale,
	)
	return i, err
}

const accountByID = `-- name: AccountByID :one
SELECT id, email, password_hash, status, email_verified_at, locale
FROM accounts WHERE id = $1
`

type AccountByIDRow struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    *string
	Status          string
	EmailVerifiedAt *time.Time
	Locale          string
}

func (q *Queries) AccountByID(ctx context.Context, id uuid.UUID) (AccountByIDRow, error) {
	row := q.db.QueryRow(ctx, accountByID, id)
	var i AccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.Locale,
	)
	return i, err
}

const accountByReferralCode = `-- name: AccountByReferralCode :one
SELECT id FROM accounts WHERE referral_code = $1 AND status = 'active'
`

// 账号邀请码（AUTH-02）。只有正常状态的账号的邀请码有效。
func (q *Queries) AccountByReferralCode(ctx context.Context, code string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, accountByReferralCode, code)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const activeVerificationCode = `-- name: ActiveVerificationCode :one
SELECT id, code_hash, attempts, expires_at FROM verification_codes
WHERE account_id = $1 AND purpose = $2 AND consumed_at IS NULL
ORDER BY id DESC LIMIT 1
FOR UPDATE
`

type ActiveVerificationCodeParams struct {
	AccountID *uuid.UUID
	Purpose   string
}

type ActiveVerificationCodeRow struct {
	ID        uuid.UUID
	CodeHash  string
	Attempts  int32
	ExpiresAt time.Time
}

// 当前有效的验证码（至多一条）。按 UUIDv7 主键取最新，不读取审计列 created_at（CONV-27）。
func (q *Queries) ActiveVerificationCode(ctx context.Context, arg ActiveVerificationCodeParams) (ActiveVerificationCodeRow, error) {
	row := q.db.QueryRow(ctx, activeVerificationCode, arg.AccountID, arg.Purpose)
	var i ActiveVerificationCodeRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
	)
	return i, err
}

const consumeVerificationCode = `-- name: ConsumeVerificationCode :exec
UPDATE verification_codes SET consumed_at = $1 WHERE id = $2
`

type ConsumeVerificationCodeParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) ConsumeVerificationCode(ctx context.Context, arg ConsumeVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, consumeVerificationCode, arg.Now, arg.ID)
	return err
}

const incrementCodeAttempts = `-- name: IncrementCodeAttempts :one
UPDATE verification_codes SET attempts = attempts + 1 WHERE id = $1 RETURNING attempts
`

func (q *Queries) IncrementCodeAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementCodeAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const insertVerificationCode = `-- name: InsertVerificationCode :exec
INSERT INTO verification_codes (account_id, purpose, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertVerificationCodeParams struct {
	AccountID *uuid.UUID
	Purpose   string
	CodeHash  string
	ExpiresAt time.Time
}

func (q *Queries) InsertVerificationCode(ctx context.Context, arg InsertVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, insertVerificationCode,
		arg.AccountID,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}

const invalidateVerificationCodes = `-- name: InvalidateVerificationCodes :exec
UPDATE verification_codes SET consumed_at = $1
WHERE account_id = $2 AND purpose = $3 AND consumed_at IS NULL
`

type InvalidateVerificationCodesParams struct {
	Now       *time.Time
	AccountID *uuid.UUID
	Purpose   string
}

// 发送新码或新链接后旧的作废（AUTH-03、AUTH-04）。
func (q *Queries) InvalidateVerificationCodes(ctx context.Context, arg InvalidateVerificationCodesParams) error {
	_, err := q.db.Exec(ctx, invalidateVerificationCodes, arg.Now, arg.AccountID, arg.Purpose)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE accounts SET email_verified_at = $1 WHERE id = $2 AND email_verified_at IS NULL
`

type MarkEmailVerifiedParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, markEmailVerified, arg.Now, arg.ID)
	return err
}

const registerAccount = `-- name: RegisterAccount :one
INSERT INTO accounts (email, password_hash, referral_code, referrer_id, locale, timezone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type RegisterAccountParams struct {
	Email        string
	PasswordHash *string
	ReferralCode string
	ReferrerID   *uuid.UUID
	Locale       string
	Timezone     *string
}

func (q *Queries) RegisterAccount(ctx context.Context, arg RegisterAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, registerAccount,
		arg.Email,
		arg.PasswordHash,
		arg.ReferralCode,
		arg.ReferrerID,
		arg.Locale,
		arg.Timezone,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE accounts SET password_hash = $1 WHERE id = $2
`

type SetPasswordHashParams struct {
	PasswordHash *string
	ID           uuid.UUID
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const verificationCodeByHash = `-- name: VerificationCodeByHash :one
SELECT id, account_id, expires_at, consumed_at FROM verification_codes
WHERE code_hash = $1 AND purpose = $2
FOR UPDATE
`

type VerificationCodeByHashParams struct {
	CodeHash string
	Purpose  string
}

type VerificationCodeByHashRow struct {
	ID         uuid.UUID
	AccountID  *uuid.UUID
	ExpiresAt  time.Time
	ConsumedAt *time.Time
}

// 找回密码链接按令牌哈希查找（AUTH-04）。
func (q *Queries) VerificationCodeByHash(ctx context.Context, arg VerificationCodeByHashParams) (VerificationCodeByHashRow, error) {
	row := q.db.QueryRow(ctx, verificationCodeByHash, arg.CodeHash, arg.Purpose)
	var i VerificationCodeByHashRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}
