// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const accountEmailExists = `-- name: AccountEmailExists :one

SELECT EXISTS (SELECT 1 FROM accounts WHERE lower(email) = lower($1::text))
`

// SPDX-License-Identifier: AGPL-3.0-or-later
// `panel admin create` 使用的查询（spec/10 AUTH-21）。
func (q *Queries) AccountEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, accountEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countRoleMembers = `-- name: CountRoleMembers :one
SELECT count(*) FROM account_roles WHERE role = $1
`

func (q *Queries) CountRoleMembers(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countRoleMembers, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (email, password_hash, email_verified_at, referral_code)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAccountParams struct {
	Email           string
	PasswordHash    *string
	EmailVerifiedAt *time.Time
	ReferralCode    string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
		arg.ReferralCode,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSharedCredential = `-- name: CreateSharedCredential :one
INSERT INTO proxy_credentials (account_id, secret_enc) VALUES ($1, $2)
RETURNING id
`

type CreateSharedCredentialParams struct {
	AccountID uuid.UUID
	SecretEnc []byte
}

func (q *Queries) CreateSharedCredential(ctx context.Context, arg CreateSharedCredentialParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSharedCredential, arg.AccountID, arg.SecretEnc)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const grantRole = `-- name: GrantRole :exec
INSERT INTO account_roles (account_id, role) VALUES ($1, $2)
`

type GrantRoleParams struct {
	AccountID uuid.UUID
	Role      string
}

func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) error {
	_, err := q.db.Exec(ctx, grantRole, arg.AccountID, arg.Role)
	return err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_id, action, target_type, target_id, diff, request_id, reason)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
`

type InsertAuditLogParams struct {
	ActorID    *uuid.UUID
	Action     string
	TargetType string
	TargetID   *string
	Diff       []byte
	RequestID  *string
	Reason     *string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Diff,
		arg.RequestID,
		arg.Reason,
	)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox (topic, payload, schema_version) VALUES ($1, $2, $3)
RETURNING id
`

type InsertOutboxEventParams struct {
	Topic         string
	Payload       []byte
	SchemaVersion int32
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent, arg.Topic, arg.Payload, arg.SchemaVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const referralCodeExists = `-- name: ReferralCodeExists :one
SELECT EXISTS (SELECT 1 FROM accounts WHERE referral_code = $1)
`

func (q *Queries) ReferralCodeExists(ctx context.Context, referralCode string) (bool, error) {
	row := q.db.QueryRow(ctx, referralCodeExists, referralCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
