// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAuditLog = `-- name: GetAuditLog :one
SELECT l.id, l.actor_id, a.email AS actor_email, l.action, l.target_type, l.target_id, l.diff,
       r.body AS reason, l.ip_prefix, l.request_id, l.created_at
FROM audit_logs l
LEFT JOIN accounts a ON a.id = l.actor_id
LEFT JOIN reason_texts r ON r.id = l.reason_id
WHERE l.id = $1
`

type GetAuditLogRow struct {
	ID         uuid.UUID
	ActorID    *uuid.UUID
	ActorEmail *string
	Action     string
	TargetType string
	TargetID   *string
	Diff       []byte
	Reason     *string
	IpPrefix   *string
	RequestID  *string
	CreatedAt  time.Time
}

func (q *Queries) GetAuditLog(ctx context.Context, id uuid.UUID) (GetAuditLogRow, error) {
	row := q.db.QueryRow(ctx, getAuditLog, id)
	var i GetAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.ActorEmail,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Diff,
		&i.Reason,
		&i.IpPrefix,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_id, action, target_type, target_id, diff, ip_prefix, request_id, reason_id)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
`

type InsertAuditLogParams struct {
	ActorID    *uuid.UUID
	Action     string
	TargetType string
	TargetID   *string
	Diff       []byte
	IpPrefix   *string
	RequestID  *string
	ReasonID   *uuid.UUID
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Diff,
		arg.IpPrefix,
		arg.RequestID,
		arg.ReasonID,
	)
	return err
}

const insertReasonText = `-- name: InsertReasonText :one

INSERT INTO reason_texts (account_id, body) VALUES ($1, $2)
RETURNING id
`

type InsertReasonTextParams struct {
	AccountID *uuid.UUID
	Body      string
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// 审计日志（spec/10 AUTH-18，spec/31 CON-09）。audit_logs 只追加（CONV-18），原因原文在 reason_texts（CONV-29）。
func (q *Queries) InsertReasonText(ctx context.Context, arg InsertReasonTextParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertReasonText, arg.AccountID, arg.Body)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT l.id, l.actor_id, a.email AS actor_email, l.action, l.target_type, l.target_id, l.diff,
       r.body AS reason, l.ip_prefix, l.request_id, l.created_at
FROM audit_logs l
LEFT JOIN accounts a ON a.id = l.actor_id
LEFT JOIN reason_texts r ON r.id = l.reason_id
WHERE ($1::uuid IS NULL OR l.actor_id = $1::uuid)
  AND ($2::text IS NULL OR l.action = $2::text)
  AND ($3::text IS NULL OR l.target_type = $3::text)
  AND ($4::text IS NULL OR l.target_id = $4::text)
  AND ($5::timestamptz IS NULL OR l.created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR l.created_at <= $6::timestamptz)
  AND ($7::timestamptz IS NULL
       OR (l.created_at, l.id) < ($7::timestamptz, $8::uuid))
ORDER BY l.created_at DESC, l.id DESC
LIMIT $9
`

type ListAuditLogsParams struct {
	ActorID     *uuid.UUID
	Action      *string
	TargetType  *string
	TargetID    *string
	CreatedFrom *time.Time
	CreatedTo   *time.Time
	CursorAt    *time.Time
	CursorID    *uuid.UUID
	MaxRows     int32
}

type ListAuditLogsRow struct {
	ID         uuid.UUID
	ActorID    *uuid.UUID
	ActorEmail *string
	Action     string
	TargetType string
	TargetID   *string
	Diff       []byte
	Reason     *string
	IpPrefix   *string
	RequestID  *string
	CreatedAt  time.Time
}

// 按 (created_at, id) 倒序的游标分页（CONV-11）；created_at 只用于展示与筛选，不参与业务判断（CONV-27）。
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.CursorAt,
		arg.CursorID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Diff,
			&i.Reason,
			&i.IpPrefix,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
