// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpPlanVersion = `-- name: BumpPlanVersion :exec
UPDATE plans SET version = version + 1 WHERE id = $1
`

// 子资源（价格行、线路组关联）变更时使套餐的 ETag 失效。
func (q *Queries) BumpPlanVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpPlanVersion, id)
	return err
}

const countGroupHolders = `-- name: CountGroupHolders :one
SELECT count(DISTINCT e.account_id)::int
FROM entitlements e
JOIN plans p ON p.id = e.plan_id
JOIN plan_groups pg ON pg.plan_id = p.id AND pg.group_id = $1
WHERE e.status IN ('active','over_quota','suspended')
  AND CASE WHEN $2::boolean
        THEN ($3::int IS NULL OR p.tier >= $3::int)
             IS DISTINCT FROM ($4::int IS NULL OR p.tier >= $4::int)
        ELSE ($3::int IS NULL OR p.tier >= $3::int)
             OR ($4::int IS NULL OR p.tier >= $4::int)
      END
`

type CountGroupHoldersParams struct {
	GroupID     uuid.UUID
	OnlyChanged bool
	OldMin      *int32
	NewMin      *int32
}

// 通过套餐可访问该线路组的账号数（影响预览，ACS-05，CON-07）：套餐关联该线路组，且
// only_changed 为真时，在 min_tier 为 old_min 与 new_min 时的可访问性不同；
// only_changed 为假时，在两者任一之下可访问。
func (q *Queries) CountGroupHolders(ctx context.Context, arg CountGroupHoldersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countGroupHolders,
		arg.GroupID,
		arg.OnlyChanged,
		arg.OldMin,
		arg.NewMin,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countGroupHosts = `-- name: CountGroupHosts :one
SELECT count(DISTINCT node_id)::int FROM node_group_members WHERE group_id = ANY($1::uuid[])
`

func (q *Queries) CountGroupHosts(ctx context.Context, groupIds []uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countGroupHosts, groupIds)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPlanHolders = `-- name: CountPlanHolders :one
SELECT count(DISTINCT account_id)::int FROM entitlements
WHERE plan_id = $1 AND status IN ('active','over_quota','suspended')
`

// 持有该套餐当前权益的账号数（影响预览，CON-07）。
func (q *Queries) CountPlanHolders(ctx context.Context, planID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPlanHolders, planID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteLocationGroup = `-- name: DeleteLocationGroup :exec
DELETE FROM location_groups WHERE id = $1
`

func (q *Queries) DeleteLocationGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLocationGroup, id)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlan, id)
	return err
}

const deletePlanGroup = `-- name: DeletePlanGroup :execrows
DELETE FROM plan_groups WHERE plan_id = $1 AND group_id = $2
`

type DeletePlanGroupParams struct {
	PlanID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) DeletePlanGroup(ctx context.Context, arg DeletePlanGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlanGroup, arg.PlanID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const discontinuePeriodPrice = `-- name: DiscontinuePeriodPrice :many
UPDATE plan_prices SET on_sale = false
WHERE plan_id = $1 AND period = $2 AND on_sale
RETURNING id
`

type DiscontinuePeriodPriceParams struct {
	PlanID uuid.UUID
	Period string
}

// 停售同一周期的在售行（改价，BIL-01），返回被停售的行。
func (q *Queries) DiscontinuePeriodPrice(ctx context.Context, arg DiscontinuePeriodPriceParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, discontinuePeriodPrice, arg.PlanID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const discontinuePlanPrice = `-- name: DiscontinuePlanPrice :one
UPDATE plan_prices SET on_sale = false WHERE id = $1 AND on_sale
RETURNING id, plan_id, period, period_days, amount_minor, currency, on_sale, created_at, updated_at
`

func (q *Queries) DiscontinuePlanPrice(ctx context.Context, id uuid.UUID) (PlanPrice, error) {
	row := q.db.QueryRow(ctx, discontinuePlanPrice, id)
	var i PlanPrice
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Period,
		&i.PeriodDays,
		&i.AmountMinor,
		&i.Currency,
		&i.OnSale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existingNodeIDs = `-- name: ExistingNodeIDs :many
SELECT id FROM nodes WHERE id = ANY($1::uuid[])
`

func (q *Queries) ExistingNodeIDs(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, existingNodeIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const freePlanExists = `-- name: FreePlanExists :one
SELECT EXISTS (SELECT 1 FROM plans WHERE kind = 'free' AND id <> $1)::boolean
`

func (q *Queries) FreePlanExists(ctx context.Context, exceptID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, freePlanExists, exceptID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getLocationGroup = `-- name: GetLocationGroup :one
SELECT g.id, g.name, g.description, g.min_tier, g.version, g.created_at, g.updated_at,
       (SELECT count(*) FROM node_group_members m WHERE m.group_id = g.id)::int AS host_count
FROM location_groups g
WHERE g.id = $1
`

type GetLocationGroupRow struct {
	ID          uuid.UUID
	Name        string
	Description *string
	MinTier     *int32
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	HostCount   int32
}

func (q *Queries) GetLocationGroup(ctx context.Context, id uuid.UUID) (GetLocationGroupRow, error) {
	row := q.db.QueryRow(ctx, getLocationGroup, id)
	var i GetLocationGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MinTier,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HostCount,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT p.id, p.name, p.description, p.tier, p.kind, p.status, p.bytes_per_cycle, p.device_limit, p.speed_limit_mbps,
       p.reset_policy, p.allow_legacy_renew, p.sort, p.version, p.created_at, p.updated_at,
       (SELECT count(*) FROM entitlements e
        WHERE e.plan_id = p.id AND e.status IN ('active','over_quota','suspended'))::int AS active_entitlement_count
FROM plans p
WHERE p.id = $1
`

type GetPlanRow struct {
	ID                     uuid.UUID
	Name                   string
	Description            *string
	Tier                   int32
	Kind                   string
	Status                 string
	BytesPerCycle          int64
	DeviceLimit            int32
	SpeedLimitMbps         *int32
	ResetPolicy            string
	AllowLegacyRenew       bool
	Sort                   int32
	Version                int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	ActiveEntitlementCount int32
}

func (q *Queries) GetPlan(ctx context.Context, id uuid.UUID) (GetPlanRow, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i GetPlanRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tier,
		&i.Kind,
		&i.Status,
		&i.BytesPerCycle,
		&i.DeviceLimit,
		&i.SpeedLimitMbps,
		&i.ResetPolicy,
		&i.AllowLegacyRenew,
		&i.Sort,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveEntitlementCount,
	)
	return i, err
}

const getPlanPrice = `-- name: GetPlanPrice :one
SELECT id, plan_id, period, period_days, amount_minor, currency, on_sale, created_at, updated_at
FROM plan_prices WHERE id = $1 AND plan_id = $2
`

type GetPlanPriceParams struct {
	ID     uuid.UUID
	PlanID uuid.UUID
}

func (q *Queries) GetPlanPrice(ctx context.Context, arg GetPlanPriceParams) (PlanPrice, error) {
	row := q.db.QueryRow(ctx, getPlanPrice, arg.ID, arg.PlanID)
	var i PlanPrice
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Period,
		&i.PeriodDays,
		&i.AmountMinor,
		&i.Currency,
		&i.OnSale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const groupMemberIDs = `-- name: GroupMemberIDs :many
SELECT node_id FROM node_group_members WHERE group_id = $1
`

func (q *Queries) GroupMemberIDs(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, groupMemberIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var node_id uuid.UUID
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupPlanIDs = `-- name: GroupPlanIDs :many
SELECT group_id, plan_id FROM plan_groups WHERE group_id = ANY($1::uuid[]) ORDER BY group_id, plan_id
`

type GroupPlanIDsRow struct {
	GroupID uuid.UUID
	PlanID  uuid.UUID
}

func (q *Queries) GroupPlanIDs(ctx context.Context, groupIds []uuid.UUID) ([]GroupPlanIDsRow, error) {
	rows, err := q.db.Query(ctx, groupPlanIDs, groupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupPlanIDsRow
	for rows.Next() {
		var i GroupPlanIDsRow
		if err := rows.Scan(&i.GroupID, &i.PlanID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLocationGroup = `-- name: InsertLocationGroup :one
INSERT INTO location_groups (name, description, min_tier) VALUES ($1, $2, $3)
RETURNING id
`

type InsertLocationGroupParams struct {
	Name        string
	Description *string
	MinTier     *int32
}

func (q *Queries) InsertLocationGroup(ctx context.Context, arg InsertLocationGroupParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertLocationGroup, arg.Name, arg.Description, arg.MinTier)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPlan = `-- name: InsertPlan :one
INSERT INTO plans (name, description, tier, kind, status, bytes_per_cycle, device_limit, speed_limit_mbps,
                   reset_policy, allow_legacy_renew, sort)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11)
RETURNING id
`

type InsertPlanParams struct {
	Name             string
	Description      *string
	Tier             int32
	Kind             string
	Status           string
	BytesPerCycle    int64
	DeviceLimit      int32
	SpeedLimitMbps   *int32
	ResetPolicy      string
	AllowLegacyRenew bool
	Sort             int32
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPlan,
		arg.Name,
		arg.Description,
		arg.Tier,
		arg.Kind,
		arg.Status,
		arg.BytesPerCycle,
		arg.DeviceLimit,
		arg.SpeedLimitMbps,
		arg.ResetPolicy,
		arg.AllowLegacyRenew,
		arg.Sort,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPlanGroup = `-- name: InsertPlanGroup :execrows
INSERT INTO plan_groups (plan_id, group_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertPlanGroupParams struct {
	PlanID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) InsertPlanGroup(ctx context.Context, arg InsertPlanGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPlanGroup, arg.PlanID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPlanPrice = `-- name: InsertPlanPrice :one
INSERT INTO plan_prices (plan_id, period, period_days, amount_minor, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, plan_id, period, period_days, amount_minor, currency, on_sale, created_at, updated_at
`

type InsertPlanPriceParams struct {
	PlanID      uuid.UUID
	Period      string
	PeriodDays  *int32
	AmountMinor int64
	Currency    string
}

func (q *Queries) InsertPlanPrice(ctx context.Context, arg InsertPlanPriceParams) (PlanPrice, error) {
	row := q.db.QueryRow(ctx, insertPlanPrice,
		arg.PlanID,
		arg.Period,
		arg.PeriodDays,
		arg.AmountMinor,
		arg.Currency,
	)
	var i PlanPrice
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Period,
		&i.PeriodDays,
		&i.AmountMinor,
		&i.Currency,
		&i.OnSale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocationGroups = `-- name: ListLocationGroups :many
SELECT g.id, g.name, g.description, g.min_tier, g.version, g.created_at, g.updated_at,
       (SELECT count(*) FROM node_group_members m WHERE m.group_id = g.id)::int AS host_count
FROM location_groups g
WHERE $1::timestamptz IS NULL
   OR (g.created_at, g.id) > ($1::timestamptz, $2::uuid)
ORDER BY g.created_at, g.id
LIMIT $3
`

type ListLocationGroupsParams struct {
	CursorAt *time.Time
	CursorID *uuid.UUID
	MaxRows  int32
}

type ListLocationGroupsRow struct {
	ID          uuid.UUID
	Name        string
	Description *string
	MinTier     *int32
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	HostCount   int32
}

// 按 (created_at, id) 升序的游标分页（CONV-11）；created_at 只用于排序展示，不参与业务判断（CONV-27）。
func (q *Queries) ListLocationGroups(ctx context.Context, arg ListLocationGroupsParams) ([]ListLocationGroupsRow, error) {
	rows, err := q.db.Query(ctx, listLocationGroups, arg.CursorAt, arg.CursorID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationGroupsRow
	for rows.Next() {
		var i ListLocationGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MinTier,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnSalePlans = `-- name: ListOnSalePlans :many
SELECT p.id, p.name, p.description, p.tier, p.kind, p.bytes_per_cycle, p.device_limit, p.speed_limit_mbps, p.reset_policy
FROM plans p
WHERE p.status = 'on_sale' AND p.kind <> 'free'
  AND EXISTS (SELECT 1 FROM plan_prices pp WHERE pp.plan_id = p.id AND pp.on_sale)
ORDER BY p.sort, p.id
LIMIT $1
`

type ListOnSalePlansRow struct {
	ID             uuid.UUID
	Name           string
	Description    *string
	Tier           int32
	Kind           string
	BytesPerCycle  int64
	DeviceLimit    int32
	SpeedLimitMbps *int32
	ResetPolicy    string
}

// 客户端接口的在售套餐：不含免费套餐与没有在售价格行的套餐，按 (sort, id)，至多 max_rows 项
// （spec/30 listPlans，spec/11 BIL-15、BIL-21）。
func (q *Queries) ListOnSalePlans(ctx context.Context, maxRows int32) ([]ListOnSalePlansRow, error) {
	rows, err := q.db.Query(ctx, listOnSalePlans, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOnSalePlansRow
	for rows.Next() {
		var i ListOnSalePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tier,
			&i.Kind,
			&i.BytesPerCycle,
			&i.DeviceLimit,
			&i.SpeedLimitMbps,
			&i.ResetPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanPrices = `-- name: ListPlanPrices :many
SELECT id, plan_id, period, period_days, amount_minor, currency, on_sale, created_at, updated_at
FROM plan_prices
WHERE plan_id = $1
  AND ($2::boolean IS NULL OR on_sale = $2::boolean)
  AND ($3::uuid IS NULL OR id < $3::uuid)
ORDER BY id DESC
LIMIT $4
`

type ListPlanPricesParams struct {
	PlanID  uuid.UUID
	OnSale  *bool
	Before  *uuid.UUID
	MaxRows int32
}

// 按 id（UUIDv7，即创建顺序）倒序的游标分页（CONV-11）。
func (q *Queries) ListPlanPrices(ctx context.Context, arg ListPlanPricesParams) ([]PlanPrice, error) {
	rows, err := q.db.Query(ctx, listPlanPrices,
		arg.PlanID,
		arg.OnSale,
		arg.Before,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanPrice
	for rows.Next() {
		var i PlanPrice
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Period,
			&i.PeriodDays,
			&i.AmountMinor,
			&i.Currency,
			&i.OnSale,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many

SELECT p.id, p.name, p.description, p.tier, p.kind, p.status, p.bytes_per_cycle, p.device_limit, p.speed_limit_mbps,
       p.reset_policy, p.allow_legacy_renew, p.sort, p.version, p.created_at, p.updated_at,
       (SELECT count(*) FROM entitlements e
        WHERE e.plan_id = p.id AND e.status IN ('active','over_quota','suspended'))::int AS active_entitlement_count
FROM plans p
WHERE ($1::text IS NULL OR p.status = $1::text)
  AND ($2::text IS NULL OR p.kind = $2::text)
  AND ($3::int IS NULL OR (p.sort, p.id) > ($3::int, $4::uuid))
ORDER BY p.sort, p.id
LIMIT $5
`

type ListPlansParams struct {
	Status     *string
	Kind       *string
	CursorSort *int32
	CursorID   *uuid.UUID
	MaxRows    int32
}

type ListPlansRow struct {
	ID                     uuid.UUID
	Name                   string
	Description            *string
	Tier                   int32
	Kind                   string
	Status                 string
	BytesPerCycle          int64
	DeviceLimit            int32
	SpeedLimitMbps         *int32
	ResetPolicy            string
	AllowLegacyRenew       bool
	Sort                   int32
	Version                int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	ActiveEntitlementCount int32
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// 套餐、价格行与线路组（spec/11，M1-04）。版本列 version 生成强 ETag（CONV-13、CONV-28），由应用加 1。
// “当前权益”指状态为 active、over_quota、suspended 的权益（spec/11 11.1）。
// 按 (sort, id) 的游标分页（CONV-11）。
func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]ListPlansRow, error) {
	rows, err := q.db.Query(ctx, listPlans,
		arg.Status,
		arg.Kind,
		arg.CursorSort,
		arg.CursorID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlansRow
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tier,
			&i.Kind,
			&i.Status,
			&i.BytesPerCycle,
			&i.DeviceLimit,
			&i.SpeedLimitMbps,
			&i.ResetPolicy,
			&i.AllowLegacyRenew,
			&i.Sort,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveEntitlementCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationGroupInUse = `-- name: LocationGroupInUse :one
SELECT (EXISTS (SELECT 1 FROM plan_groups pg WHERE pg.group_id = $1)
     OR EXISTS (SELECT 1 FROM node_group_members m WHERE m.group_id = $1))::boolean
`

// 仍被套餐引用或仍有节点的线路组不能删除（ACS-06）。
func (q *Queries) LocationGroupInUse(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, locationGroupInUse, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const locationGroupTiers = `-- name: LocationGroupTiers :many
SELECT id, min_tier FROM location_groups WHERE id = ANY($1::uuid[])
`

type LocationGroupTiersRow struct {
	ID      uuid.UUID
	MinTier *int32
}

// 给定线路组的 min_tier；不存在的 ID 不返回。
func (q *Queries) LocationGroupTiers(ctx context.Context, ids []uuid.UUID) ([]LocationGroupTiersRow, error) {
	rows, err := q.db.Query(ctx, locationGroupTiers, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocationGroupTiersRow
	for rows.Next() {
		var i LocationGroupTiersRow
		if err := rows.Scan(&i.ID, &i.MinTier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLocationGroup = `-- name: LockLocationGroup :one
SELECT id, name, description, min_tier, version FROM location_groups WHERE id = $1 FOR UPDATE
`

type LockLocationGroupRow struct {
	ID          uuid.UUID
	Name        string
	Description *string
	MinTier     *int32
	Version     int64
}

func (q *Queries) LockLocationGroup(ctx context.Context, id uuid.UUID) (LockLocationGroupRow, error) {
	row := q.db.QueryRow(ctx, lockLocationGroup, id)
	var i LockLocationGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MinTier,
		&i.Version,
	)
	return i, err
}

const lockPlan = `-- name: LockPlan :one
SELECT id, name, description, tier, kind, status, bytes_per_cycle, device_limit, speed_limit_mbps,
       reset_policy, allow_legacy_renew, sort, version
FROM plans WHERE id = $1 FOR UPDATE
`

type LockPlanRow struct {
	ID               uuid.UUID
	Name             string
	Description      *string
	Tier             int32
	Kind             string
	Status           string
	BytesPerCycle    int64
	DeviceLimit      int32
	SpeedLimitMbps   *int32
	ResetPolicy      string
	AllowLegacyRenew bool
	Sort             int32
	Version          int64
}

func (q *Queries) LockPlan(ctx context.Context, id uuid.UUID) (LockPlanRow, error) {
	row := q.db.QueryRow(ctx, lockPlan, id)
	var i LockPlanRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tier,
		&i.Kind,
		&i.Status,
		&i.BytesPerCycle,
		&i.DeviceLimit,
		&i.SpeedLimitMbps,
		&i.ResetPolicy,
		&i.AllowLegacyRenew,
		&i.Sort,
		&i.Version,
	)
	return i, err
}

const lockPlanPrice = `-- name: LockPlanPrice :one
SELECT id, plan_id, period, period_days, amount_minor, currency, on_sale, created_at, updated_at
FROM plan_prices WHERE id = $1 AND plan_id = $2 FOR UPDATE
`

type LockPlanPriceParams struct {
	ID     uuid.UUID
	PlanID uuid.UUID
}

func (q *Queries) LockPlanPrice(ctx context.Context, arg LockPlanPriceParams) (PlanPrice, error) {
	row := q.db.QueryRow(ctx, lockPlanPrice, arg.ID, arg.PlanID)
	var i PlanPrice
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Period,
		&i.PeriodDays,
		&i.AmountMinor,
		&i.Currency,
		&i.OnSale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const onSalePrices = `-- name: OnSalePrices :many
SELECT id, plan_id, period, period_days, amount_minor, currency, on_sale, created_at, updated_at
FROM plan_prices WHERE plan_id = ANY($1::uuid[]) AND on_sale
ORDER BY plan_id, id
`

func (q *Queries) OnSalePrices(ctx context.Context, planIds []uuid.UUID) ([]PlanPrice, error) {
	rows, err := q.db.Query(ctx, onSalePrices, planIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanPrice
	for rows.Next() {
		var i PlanPrice
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Period,
			&i.PeriodDays,
			&i.AmountMinor,
			&i.Currency,
			&i.OnSale,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const planGroupIDs = `-- name: PlanGroupIDs :many
SELECT plan_id, group_id FROM plan_groups WHERE plan_id = ANY($1::uuid[]) ORDER BY plan_id, group_id
`

type PlanGroupIDsRow struct {
	PlanID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) PlanGroupIDs(ctx context.Context, planIds []uuid.UUID) ([]PlanGroupIDsRow, error) {
	rows, err := q.db.Query(ctx, planGroupIDs, planIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanGroupIDsRow
	for rows.Next() {
		var i PlanGroupIDsRow
		if err := rows.Scan(&i.PlanID, &i.GroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const planRegionCounts = `-- name: PlanRegionCounts :many
SELECT pg.plan_id, count(DISTINCT n.region_code)::int AS regions
FROM plan_groups pg
JOIN plans p ON p.id = pg.plan_id
JOIN location_groups g ON g.id = pg.group_id AND (g.min_tier IS NULL OR p.tier >= g.min_tier)
JOIN node_group_members m ON m.group_id = g.id
JOIN nodes n ON n.id = m.node_id
WHERE pg.plan_id = ANY($1::uuid[])
GROUP BY pg.plan_id
`

type PlanRegionCountsRow struct {
	PlanID  uuid.UUID
	Regions int32
}

// 套餐可访问的地区数：关联且满足 min_tier 的线路组中，节点的 region_code 去重（spec/30 Plan.location_count）。
func (q *Queries) PlanRegionCounts(ctx context.Context, planIds []uuid.UUID) ([]PlanRegionCountsRow, error) {
	rows, err := q.db.Query(ctx, planRegionCounts, planIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanRegionCountsRow
	for rows.Next() {
		var i PlanRegionCountsRow
		if err := rows.Scan(&i.PlanID, &i.Regions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const planUsage = `-- name: PlanUsage :one
SELECT EXISTS (SELECT 1 FROM plan_prices pp WHERE pp.plan_id = $1)::boolean AS has_prices,
       EXISTS (SELECT 1 FROM entitlements e WHERE e.plan_id = $1)::boolean AS has_entitlements,
       (SELECT count(*) FROM plan_prices pp WHERE pp.plan_id = $1 AND pp.on_sale)::int AS on_sale_prices
`

type PlanUsageRow struct {
	HasPrices       bool
	HasEntitlements bool
	OnSalePrices    int32
}

// 套餐是否有价格行、是否有权益（任何状态），用于删除、修改类型与改回 draft 的判断。
func (q *Queries) PlanUsage(ctx context.Context, id uuid.UUID) (PlanUsageRow, error) {
	row := q.db.QueryRow(ctx, planUsage, id)
	var i PlanUsageRow
	err := row.Scan(&i.HasPrices, &i.HasEntitlements, &i.OnSalePrices)
	return i, err
}

const updateLocationGroup = `-- name: UpdateLocationGroup :exec
UPDATE location_groups SET name = $1, description = $2, min_tier = $3,
       version = version + 1
WHERE id = $4
`

type UpdateLocationGroupParams struct {
	Name        string
	Description *string
	MinTier     *int32
	ID          uuid.UUID
}

func (q *Queries) UpdateLocationGroup(ctx context.Context, arg UpdateLocationGroupParams) error {
	_, err := q.db.Exec(ctx, updateLocationGroup,
		arg.Name,
		arg.Description,
		arg.MinTier,
		arg.ID,
	)
	return err
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans SET name = $1, description = $2, tier = $3, kind = $4,
       status = $5, bytes_per_cycle = $6, device_limit = $7,
       speed_limit_mbps = $8, reset_policy = $9,
       allow_legacy_renew = $10, sort = $11, version = version + 1
WHERE id = $12
`

type UpdatePlanParams struct {
	Name             string
	Description      *string
	Tier             int32
	Kind             string
	Status           string
	BytesPerCycle    int64
	DeviceLimit      int32
	SpeedLimitMbps   *int32
	ResetPolicy      string
	AllowLegacyRenew bool
	Sort             int32
	ID               uuid.UUID
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.Exec(ctx, updatePlan,
		arg.Name,
		arg.Description,
		arg.Tier,
		arg.Kind,
		arg.Status,
		arg.BytesPerCycle,
		arg.DeviceLimit,
		arg.SpeedLimitMbps,
		arg.ResetPolicy,
		arg.AllowLegacyRenew,
		arg.Sort,
		arg.ID,
	)
	return err
}
