// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const credentialSlots = `-- name: CredentialSlots :many

SELECT d.id, c.id AS credential_id
FROM devices d
LEFT JOIN proxy_credentials c ON c.device_id = d.id AND c.revoked_at IS NULL
WHERE d.account_id = $1 AND d.platform <> 'web' AND d.revoked_at IS NULL
ORDER BY d.last_seen_at DESC NULLS LAST, d.id
FOR NO KEY UPDATE OF d
`

type CredentialSlotsRow struct {
	ID           uuid.UUID
	CredentialID *uuid.UUID
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// 设备列表、移除设备与设备凭据的分配（spec/10 AUTH-13–15，spec/30 /v1/me/devices）。
// 未吊销的非 web 设备及其未吊销的凭据，按 last_seen_at 从近到远排序（AUTH-14）。调用方已持有账号行锁。
func (q *Queries) CredentialSlots(ctx context.Context, accountID uuid.UUID) ([]CredentialSlotsRow, error) {
	rows, err := q.db.Query(ctx, credentialSlots, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CredentialSlotsRow
	for rows.Next() {
		var i CredentialSlotsRow
		if err := rows.Scan(&i.ID, &i.CredentialID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deviceLimit = `-- name: DeviceLimit :one
SELECT COALESCE(
  (SELECT e.device_limit FROM entitlements e WHERE e.account_id = $1 AND e.status IN ('active', 'over_quota', 'suspended')),
  (SELECT (s.value #>> '{}')::int FROM settings s WHERE s.key = 'free_device_limit'),
  1)::int AS device_limit
`

// 显示用的设备上限，与 GET /v1/me 的 device_limit 口径相同：当前权益快照，没有当前权益时取 free_device_limit（默认 1）。
func (q *Queries) DeviceLimit(ctx context.Context, accountID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, deviceLimit, accountID)
	var device_limit int32
	err := row.Scan(&device_limit)
	return device_limit, err
}

const listDevices = `-- name: ListDevices :many
SELECT d.id, d.platform, d.model, d.app_version, d.created_at, d.last_seen_at,
       (SELECT s.ip_prefix FROM sessions s
        WHERE s.account_id = d.account_id AND s.device_id = d.id AND s.revoked_at IS NULL
        ORDER BY s.id DESC LIMIT 1) AS ip_prefix,
       (d.id IS NOT DISTINCT FROM (SELECT s.device_id FROM sessions s WHERE s.id = $1))::bool AS is_current,
       EXISTS (SELECT 1 FROM proxy_credentials c WHERE c.device_id = d.id AND c.revoked_at IS NULL)::bool AS has_credential
FROM devices d
WHERE d.account_id = $2 AND d.revoked_at IS NULL
ORDER BY d.last_seen_at DESC NULLS LAST, d.id
`

type ListDevicesParams struct {
	SessionID uuid.UUID
	AccountID uuid.UUID
}

type ListDevicesRow struct {
	ID            uuid.UUID
	Platform      string
	Model         *string
	AppVersion    *string
	CreatedAt     time.Time
	LastSeenAt    *time.Time
	IpPrefix      *string
	IsCurrent     bool
	HasCredential bool
}

// 未吊销的设备（含 web 设备）。ip_prefix 取该设备最近的未吊销会话；is_current 为发起请求的会话所属的设备。
func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]ListDevicesRow, error) {
	rows, err := q.db.Query(ctx, listDevices, arg.SessionID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesRow
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Model,
			&i.AppVersion,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.IpPrefix,
			&i.IsCurrent,
			&i.HasCredential,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwnDevice = `-- name: LockOwnDevice :one
SELECT id FROM devices WHERE id = $1 AND account_id = $2 AND revoked_at IS NULL FOR NO KEY UPDATE
`

type LockOwnDeviceParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

// 移除设备（AUTH-15）：只锁定本账号未吊销的设备；他人的设备与不存在的设备同样找不到（CONV-15）。
// 设备行一律取 FOR NO KEY UPDATE：刷新令牌插入子会话时对设备行取 FOR KEY SHARE（外键），两者不冲突。
func (q *Queries) LockOwnDevice(ctx context.Context, arg LockOwnDeviceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockOwnDevice, arg.ID, arg.AccountID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeCredential = `-- name: RevokeCredential :exec
UPDATE proxy_credentials SET revoked_at = $1 WHERE id = $2 AND revoked_at IS NULL
`

type RevokeCredentialParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) RevokeCredential(ctx context.Context, arg RevokeCredentialParams) error {
	_, err := q.db.Exec(ctx, revokeCredential, arg.Now, arg.ID)
	return err
}

const touchDeviceSeen = `-- name: TouchDeviceSeen :exec
UPDATE devices SET last_seen_at = $1
WHERE id = (SELECT id FROM devices WHERE devices.id = $2 AND revoked_at IS NULL FOR NO KEY UPDATE SKIP LOCKED)
`

type TouchDeviceSeenParams struct {
	Now *time.Time
	ID  uuid.UUID
}

// 刷新令牌时记录设备最近活跃时间（AUTH-14 的排序依据）。设备行正被移除或分配凭据时跳过，
// 不在持有会话行锁时等待设备行锁（移除设备先锁设备、再吊销会话）。
func (q *Queries) TouchDeviceSeen(ctx context.Context, arg TouchDeviceSeenParams) error {
	_, err := q.db.Exec(ctx, touchDeviceSeen, arg.Now, arg.ID)
	return err
}
