// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const exportToken = `-- name: ExportToken :one
SELECT token_enc, rotated_at FROM export_tokens WHERE account_id = $1
`

type ExportTokenRow struct {
	TokenEnc  []byte
	RotatedAt time.Time
}

func (q *Queries) ExportToken(ctx context.Context, accountID uuid.UUID) (ExportTokenRow, error) {
	row := q.db.QueryRow(ctx, exportToken, accountID)
	var i ExportTokenRow
	err := row.Scan(&i.TokenEnc, &i.RotatedAt)
	return i, err
}

const insertExportToken = `-- name: InsertExportToken :exec

INSERT INTO export_tokens (account_id, token_hash, token_enc, rotated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id) DO NOTHING
`

type InsertExportTokenParams struct {
	AccountID uuid.UUID
	TokenHash string
	TokenEnc  []byte
	Now       time.Time
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// 第三方客户端的导出令牌（spec/10 AUTH-16，CONV-20 例外：token_hash 用于查找，token_enc 用于再次显示）。
// 账号创建时生成；读取导入链接时若不存在（AUTH-22 的凭据重置会删除）同样补建。已有令牌时不变。
func (q *Queries) InsertExportToken(ctx context.Context, arg InsertExportTokenParams) error {
	_, err := q.db.Exec(ctx, insertExportToken,
		arg.AccountID,
		arg.TokenHash,
		arg.TokenEnc,
		arg.Now,
	)
	return err
}

const replaceExportToken = `-- name: ReplaceExportToken :exec
INSERT INTO export_tokens (account_id, token_hash, token_enc, rotated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id) DO UPDATE SET token_hash = EXCLUDED.token_hash, token_enc = EXCLUDED.token_enc, rotated_at = EXCLUDED.rotated_at
`

type ReplaceExportTokenParams struct {
	AccountID uuid.UUID
	TokenHash string
	TokenEnc  []byte
	Now       time.Time
}

// 重置导出令牌（AUTH-16）：旧令牌的哈希随之删除，旧链接立即失效。
func (q *Queries) ReplaceExportToken(ctx context.Context, arg ReplaceExportTokenParams) error {
	_, err := q.db.Exec(ctx, replaceExportToken,
		arg.AccountID,
		arg.TokenHash,
		arg.TokenEnc,
		arg.Now,
	)
	return err
}

const revokeSharedCredential = `-- name: RevokeSharedCredential :many
UPDATE proxy_credentials SET revoked_at = $1
WHERE account_id = $2 AND device_id IS NULL AND revoked_at IS NULL
RETURNING id
`

type RevokeSharedCredentialParams struct {
	Now       *time.Time
	AccountID uuid.UUID
}

// 吊销账号的共用凭据（device_id 为空），返回凭据 ID 以写 credential.changed。
func (q *Queries) RevokeSharedCredential(ctx context.Context, arg RevokeSharedCredentialParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeSharedCredential, arg.Now, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
