// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one

INSERT INTO idempotency_keys (key, account_id, route, request_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
RETURNING id
`

type ClaimIdempotencyKeyParams struct {
	Key         uuid.UUID
	AccountID   *uuid.UUID
	Route       string
	RequestHash []byte
	ExpiresAt   time.Time
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// Idempotency-Key（CONV-12）。response_status 为空表示首个请求仍在处理；request_hash 为请求体的 HMAC-SHA256。
// 抢占幂等键：插入成功返回新行 ID；已存在（包括并发插入）时返回空行。
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.Key,
		arg.AccountID,
		arg.Route,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :execrows
UPDATE idempotency_keys
SET response_status = $1, response_headers = $2, response_body = $3
WHERE id = $4 AND response_status IS NULL
`

type CompleteIdempotencyKeyParams struct {
	ResponseStatus  *int32
	ResponseHeaders []byte
	ResponseBody    []byte
	ID              uuid.UUID
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at <= $1
`

// worker 每小时清理过期记录（CONV-12）。
func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE id = $1
`

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, id)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, route, request_hash, response_status, response_headers, response_body, expires_at
FROM idempotency_keys
WHERE key = $1
  AND (($2::uuid IS NOT NULL AND account_id = $2::uuid)
    OR ($2::uuid IS NULL AND account_id IS NULL AND route = $3))
`

type GetIdempotencyKeyParams struct {
	Key       uuid.UUID
	AccountID *uuid.UUID
	Route     string
}

type GetIdempotencyKeyRow struct {
	ID              uuid.UUID
	Route           string
	RequestHash     []byte
	ResponseStatus  *int32
	ResponseHeaders []byte
	ResponseBody    []byte
	ExpiresAt       time.Time
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Key, arg.AccountID, arg.Route)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.Route,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.ExpiresAt,
	)
	return i, err
}
