// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE staff_invitations SET accepted_at = $1, account_id = $2 WHERE id = $3
`

type AcceptInvitationParams struct {
	Now       *time.Time
	AccountID *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) error {
	_, err := q.db.Exec(ctx, acceptInvitation, arg.Now, arg.AccountID, arg.ID)
	return err
}

const deleteExportToken = `-- name: DeleteExportToken :exec
DELETE FROM export_tokens WHERE account_id = $1
`

func (q *Queries) DeleteExportToken(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExportToken, accountID)
	return err
}

const getInvitation = `-- name: GetInvitation :one
SELECT i.id, i.email, i.inviter_id, i.expires_at, i.accepted_at, i.revoked_at, i.created_at,
       COALESCE((SELECT array_agg(ir.role ORDER BY ir.role) FROM staff_invitation_roles ir
                 WHERE ir.staff_invitation_id = i.id), '{}')::text[] AS roles
FROM staff_invitations i
WHERE i.id = $1
`

type GetInvitationRow struct {
	ID         uuid.UUID
	Email      string
	InviterID  uuid.UUID
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	RevokedAt  *time.Time
	CreatedAt  time.Time
	Roles      []string
}

func (q *Queries) GetInvitation(ctx context.Context, id uuid.UUID) (GetInvitationRow, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i GetInvitationRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviterID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Roles,
	)
	return i, err
}

const insertInvitation = `-- name: InsertInvitation :one

INSERT INTO staff_invitations (email, token_hash, inviter_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type InsertInvitationParams struct {
	Email     string
	TokenHash string
	InviterID uuid.UUID
	ExpiresAt time.Time
}

type InsertInvitationRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// 管理员邀请（spec/10 AUTH-22）。状态由列推导：accepted、revoked、expired（按注入的时钟，CONV-27）、pending。
func (q *Queries) InsertInvitation(ctx context.Context, arg InsertInvitationParams) (InsertInvitationRow, error) {
	row := q.db.QueryRow(ctx, insertInvitation,
		arg.Email,
		arg.TokenHash,
		arg.InviterID,
		arg.ExpiresAt,
	)
	var i InsertInvitationRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertInvitationRole = `-- name: InsertInvitationRole :exec
INSERT INTO staff_invitation_roles (staff_invitation_id, role) VALUES ($1, $2)
`

type InsertInvitationRoleParams struct {
	StaffInvitationID uuid.UUID
	Role              string
}

func (q *Queries) InsertInvitationRole(ctx context.Context, arg InsertInvitationRoleParams) error {
	_, err := q.db.Exec(ctx, insertInvitationRole, arg.StaffInvitationID, arg.Role)
	return err
}

const invalidateAllVerificationCodes = `-- name: InvalidateAllVerificationCodes :exec
UPDATE verification_codes SET consumed_at = $1 WHERE account_id = $2 AND consumed_at IS NULL
`

type InvalidateAllVerificationCodesParams struct {
	Now       *time.Time
	AccountID *uuid.UUID
}

// 作废账号尚未使用的全部验证码与找回密码令牌。
func (q *Queries) InvalidateAllVerificationCodes(ctx context.Context, arg InvalidateAllVerificationCodesParams) error {
	_, err := q.db.Exec(ctx, invalidateAllVerificationCodes, arg.Now, arg.AccountID)
	return err
}

const invitationRoles = `-- name: InvitationRoles :many
SELECT role FROM staff_invitation_roles WHERE staff_invitation_id = $1 ORDER BY role
`

func (q *Queries) InvitationRoles(ctx context.Context, staffInvitationID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, invitationRoles, staffInvitationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitations = `-- name: ListInvitations :many
SELECT i.id, i.email, i.inviter_id, i.expires_at, i.accepted_at, i.revoked_at, i.created_at,
       COALESCE((SELECT array_agg(ir.role ORDER BY ir.role) FROM staff_invitation_roles ir
                 WHERE ir.staff_invitation_id = i.id), '{}')::text[] AS roles
FROM staff_invitations i
WHERE ($1::text IS NULL OR $1::text = CASE
         WHEN i.accepted_at IS NOT NULL THEN 'accepted'
         WHEN i.revoked_at IS NOT NULL THEN 'revoked'
         WHEN i.expires_at <= $2 THEN 'expired'
         ELSE 'pending' END)
  AND ($3::uuid IS NULL OR i.id < $3::uuid)
ORDER BY i.id DESC
LIMIT $4
`

type ListInvitationsParams struct {
	Status  *string
	Now     time.Time
	Before  *uuid.UUID
	MaxRows int32
}

type ListInvitationsRow struct {
	ID         uuid.UUID
	Email      string
	InviterID  uuid.UUID
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	RevokedAt  *time.Time
	CreatedAt  time.Time
	Roles      []string
}

// 按 ID（UUIDv7）倒序分页（CONV-11）。
func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations,
		arg.Status,
		arg.Now,
		arg.Before,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitationsRow
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.InviterID,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountByEmail = `-- name: LockAccountByEmail :one
SELECT id, status, email_verified_at, locale FROM accounts WHERE lower(email) = lower($1::text) FOR NO KEY UPDATE
`

type LockAccountByEmailRow struct {
	ID              uuid.UUID
	Status          string
	EmailVerifiedAt *time.Time
	Locale          string
}

// 接受邀请时锁定被邀请邮箱的账号（AUTH-22 按账号状态处理）。锁的模式与顺序同 LockAccount：FOR NO KEY UPDATE，
// 先账号行、再会话与设备行，不阻塞刷新令牌插入子会话时的外键检查。
func (q *Queries) LockAccountByEmail(ctx context.Context, email string) (LockAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, lockAccountByEmail, email)
	var i LockAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.Locale,
	)
	return i, err
}

const lockInvitation = `-- name: LockInvitation :one
SELECT id, email, inviter_id, expires_at, accepted_at, revoked_at FROM staff_invitations WHERE id = $1 FOR UPDATE
`

type LockInvitationRow struct {
	ID         uuid.UUID
	Email      string
	InviterID  uuid.UUID
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	RevokedAt  *time.Time
}

func (q *Queries) LockInvitation(ctx context.Context, id uuid.UUID) (LockInvitationRow, error) {
	row := q.db.QueryRow(ctx, lockInvitation, id)
	var i LockInvitationRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviterID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockInvitationByToken = `-- name: LockInvitationByToken :one
SELECT id, email, inviter_id, expires_at, accepted_at, revoked_at FROM staff_invitations
WHERE token_hash = $1 FOR UPDATE
`

type LockInvitationByTokenRow struct {
	ID         uuid.UUID
	Email      string
	InviterID  uuid.UUID
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	RevokedAt  *time.Time
}

// 接受邀请时锁定邀请行，令牌只能使用一次（AUTH-22）。
func (q *Queries) LockInvitationByToken(ctx context.Context, tokenHash string) (LockInvitationByTokenRow, error) {
	row := q.db.QueryRow(ctx, lockInvitationByToken, tokenHash)
	var i LockInvitationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviterID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
	)
	return i, err
}

const pendingInvitationExists = `-- name: PendingInvitationExists :one
SELECT EXISTS (
  SELECT 1 FROM staff_invitations
  WHERE lower(email) = lower($1::text) AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > $2
)
`

type PendingInvitationExistsParams struct {
	Email string
	Now   time.Time
}

func (q *Queries) PendingInvitationExists(ctx context.Context, arg PendingInvitationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, pendingInvitationExists, arg.Email, arg.Now)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeAccountCredentials = `-- name: RevokeAccountCredentials :many
UPDATE proxy_credentials SET revoked_at = $1
WHERE account_id = $2 AND revoked_at IS NULL
RETURNING id
`

type RevokeAccountCredentialsParams struct {
	Now       *time.Time
	AccountID uuid.UUID
}

// 吊销账号的全部代理凭据（设备凭据与共用凭据），返回凭据 ID 以写 credential.changed。
func (q *Queries) RevokeAccountCredentials(ctx context.Context, arg RevokeAccountCredentialsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeAccountCredentials, arg.Now, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccountDevices = `-- name: RevokeAccountDevices :exec
UPDATE devices SET revoked_at = $1 WHERE account_id = $2 AND revoked_at IS NULL
`

type RevokeAccountDevicesParams struct {
	Now       *time.Time
	AccountID uuid.UUID
}

// 接受邀请时重置未验证邮箱账号的凭据（AUTH-22 第 3 项）：吊销全部设备。
func (q *Queries) RevokeAccountDevices(ctx context.Context, arg RevokeAccountDevicesParams) error {
	_, err := q.db.Exec(ctx, revokeAccountDevices, arg.Now, arg.AccountID)
	return err
}

const revokeInvitation = `-- name: RevokeInvitation :exec
UPDATE staff_invitations SET revoked_at = $1 WHERE id = $2
`

type RevokeInvitationParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) error {
	_, err := q.db.Exec(ctx, revokeInvitation, arg.Now, arg.ID)
	return err
}

const revokePendingInvitationsBy = `-- name: RevokePendingInvitationsBy :many
UPDATE staff_invitations SET revoked_at = $1
WHERE inviter_id = $2 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > $1
RETURNING id
`

type RevokePendingInvitationsByParams struct {
	Now       *time.Time
	InviterID uuid.UUID
}

// 超级管理员失去 superadmin 时撤销其发出的 pending 邀请（AUTH-22）。
func (q *Queries) RevokePendingInvitationsBy(ctx context.Context, arg RevokePendingInvitationsByParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokePendingInvitationsBy, arg.Now, arg.InviterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staffEmailExists = `-- name: StaffEmailExists :one
SELECT EXISTS (
  SELECT 1 FROM accounts a JOIN account_roles ar ON ar.account_id = a.id WHERE lower(a.email) = lower($1::text)
)
`

func (q *Queries) StaffEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, staffEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
