// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: me.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMe = `-- name: GetMe :one

SELECT a.id, a.email, a.email_verified_at, a.status, a.locale,
       COALESCE(a.timezone, (SELECT s.value #>> '{}' FROM settings s WHERE s.key = 'site_timezone'), 'Asia/Shanghai')::text AS timezone, a.referral_code, a.auto_renew, a.created_at,
       t.enabled_at AS totp_enabled_at,
       e.status AS entitlement_status, p.kind AS plan_kind, e.device_limit AS entitlement_device_limit,
       COALESCE((SELECT (s.value #>> '{}')::int FROM settings s WHERE s.key = 'free_device_limit'), 1)::int AS free_device_limit
FROM accounts a
LEFT JOIN mfa_totp t ON t.account_id = a.id
LEFT JOIN entitlements e ON e.account_id = a.id AND e.status IN ('active', 'over_quota', 'suspended')
LEFT JOIN plans p ON p.id = e.plan_id
WHERE a.id = $1
`

type GetMeRow struct {
	ID                     uuid.UUID
	Email                  string
	EmailVerifiedAt        *time.Time
	Status                 string
	Locale                 string
	Timezone               string
	ReferralCode           string
	AutoRenew              bool
	CreatedAt              time.Time
	TotpEnabledAt          *time.Time
	EntitlementStatus      *string
	PlanKind               *string
	EntitlementDeviceLimit *int32
	FreeDeviceLimit        int32
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// 当前账号信息（spec/30 GET /v1/me）。
// entitlement_status：当前权益（active、over_quota、suspended，至多一条，BIL-05）属于免费套餐时为 free，
// 否则为其状态；没有当前权益时为 none（spec/11 11.1）。
// timezone：账号未设置时取站点时区 site_timezone，默认 Asia/Shanghai（CONV-26）。
// device_limit：取当前权益快照；没有当前权益时取设置项 free_device_limit，默认 1（spec/10 AUTH-14）。
func (q *Queries) GetMe(ctx context.Context, id uuid.UUID) (GetMeRow, error) {
	row := q.db.QueryRow(ctx, getMe, id)
	var i GetMeRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.ReferralCode,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.TotpEnabledAt,
		&i.EntitlementStatus,
		&i.PlanKind,
		&i.EntitlementDeviceLimit,
		&i.FreeDeviceLimit,
	)
	return i, err
}
