// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTotp = `-- name: DeleteTotp :exec
DELETE FROM mfa_totp WHERE account_id = $1
`

func (q *Queries) DeleteTotp(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTotp, accountID)
	return err
}

const getTotp = `-- name: GetTotp :one

SELECT secret_enc, recovery_hashes, last_used_step, enabled_at FROM mfa_totp
WHERE account_id = $1
FOR UPDATE
`

type GetTotpRow struct {
	SecretEnc      []byte
	RecoveryHashes []string
	LastUsedStep   *int64
	EnabledAt      *time.Time
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// 二次验证（spec/10 AUTH-11、AUTH-12、AUTH-20、AUTH-23）。
func (q *Queries) GetTotp(ctx context.Context, accountID uuid.UUID) (GetTotpRow, error) {
	row := q.db.QueryRow(ctx, getTotp, accountID)
	var i GetTotpRow
	err := row.Scan(
		&i.SecretEnc,
		&i.RecoveryHashes,
		&i.LastUsedStep,
		&i.EnabledAt,
	)
	return i, err
}

const hasStaffRole = `-- name: HasStaffRole :one
SELECT EXISTS (SELECT 1 FROM account_roles WHERE account_id = $1)
`

// 持有任一管理员角色（AUTH-12：管理员必须启用二次验证）。
func (q *Queries) HasStaffRole(ctx context.Context, accountID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasStaffRole, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertTotp = `-- name: InsertTotp :exec
INSERT INTO mfa_totp (account_id, secret_enc, recovery_hashes, last_used_step, enabled_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertTotpParams struct {
	AccountID      uuid.UUID
	SecretEnc      []byte
	RecoveryHashes []string
	LastUsedStep   *int64
	EnabledAt      *time.Time
}

func (q *Queries) InsertTotp(ctx context.Context, arg InsertTotpParams) error {
	_, err := q.db.Exec(ctx, insertTotp,
		arg.AccountID,
		arg.SecretEnc,
		arg.RecoveryHashes,
		arg.LastUsedStep,
		arg.EnabledAt,
	)
	return err
}

const revokeConsoleSessions = `-- name: RevokeConsoleSessions :many
UPDATE sessions SET revoked_at = $1
WHERE account_id = $2 AND audience = 'console' AND revoked_at IS NULL
RETURNING id
`

type RevokeConsoleSessionsParams struct {
	Now       *time.Time
	AccountID uuid.UUID
}

// 管理员的二次验证设置变化时吊销其全部管理会话（AUTH-21）。
func (q *Queries) RevokeConsoleSessions(ctx context.Context, arg RevokeConsoleSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeConsoleSessions, arg.Now, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOtherSessions = `-- name: RevokeOtherSessions :many
UPDATE sessions SET revoked_at = $1
WHERE account_id = $2 AND revoked_at IS NULL AND id <> $3
RETURNING id
`

type RevokeOtherSessionsParams struct {
	Now       *time.Time
	AccountID uuid.UUID
	Keep      uuid.UUID
}

// 修改密码后吊销除当前会话外的全部会话（spec/30 PUT /v1/me/password）。
func (q *Queries) RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeOtherSessions, arg.Now, arg.AccountID, arg.Keep)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecoveryHashes = `-- name: SetRecoveryHashes :exec
UPDATE mfa_totp SET recovery_hashes = $1 WHERE account_id = $2
`

type SetRecoveryHashesParams struct {
	RecoveryHashes []string
	AccountID      uuid.UUID
}

func (q *Queries) SetRecoveryHashes(ctx context.Context, arg SetRecoveryHashesParams) error {
	_, err := q.db.Exec(ctx, setRecoveryHashes, arg.RecoveryHashes, arg.AccountID)
	return err
}

const setTotpStep = `-- name: SetTotpStep :exec
UPDATE mfa_totp SET last_used_step = $1 WHERE account_id = $2
`

type SetTotpStepParams struct {
	Step      *int64
	AccountID uuid.UUID
}

func (q *Queries) SetTotpStep(ctx context.Context, arg SetTotpStepParams) error {
	_, err := q.db.Exec(ctx, setTotpStep, arg.Step, arg.AccountID)
	return err
}
