// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    *string
	Status          string
	EmailVerifiedAt *time.Time
	Locale          string
	Timezone        *string
	ReferralCode    string
	ReferrerID      *uuid.UUID
	AutoRenew       bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AccountBalance struct {
	AccountID    uuid.UUID
	Currency     string
	BalanceMinor int64
}

type AccountRole struct {
	AccountID uuid.UUID
	Role      string
	CreatedAt time.Time
}

type Addon struct {
	ID            uuid.UUID
	EntitlementID uuid.UUID
	Kind          string
	AddonPriceID  *uuid.UUID
	BytesTotal    int64
	BytesUsed     int64
	DeviceSlots   int32
	PaidMinor     int64
	ExpiresAt     *time.Time
	OrderID       *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AddonPrice struct {
	ID          uuid.UUID
	Kind        string
	BytesTotal  int64
	DeviceSlots int32
	AmountMinor int64
	Currency    string
	OnSale      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Announcement struct {
	ID        uuid.UUID
	Title     []byte
	BodyMd    []byte
	Audience  string
	PlanIds   []uuid.UUID
	Pinned    bool
	StartsAt  time.Time
	EndsAt    *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Article struct {
	ID        uuid.UUID
	Slug      string
	Category  string
	Platforms []string
	Title     []byte
	BodyMd    []byte
	Published bool
	Sort      int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AuditLog struct {
	ID         uuid.UUID
	ActorID    *uuid.UUID
	Action     string
	TargetType string
	TargetID   *string
	Diff       []byte
	IpPrefix   *string
	RequestID  *string
	Reason     *string
	CreatedAt  time.Time
}

type ConsumedEvent struct {
	EventID   uuid.UUID
	Consumer  string
	CreatedAt time.Time
}

type Coupon struct {
	ID                uuid.UUID
	CodeHash          string
	Kind              string
	Value             int64
	PlanIds           []uuid.UUID
	Periods           []string
	OrderTypes        []string
	MaxUses           *int32
	MaxUsesPerAccount int32
	StartsAt          *time.Time
	EndsAt            *time.Time
	DisabledAt        *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type CouponRedemption struct {
	CouponID  uuid.UUID
	AccountID uuid.UUID
	OrderID   uuid.UUID
	CreatedAt time.Time
}

type CreditLedger struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	AmountMinor int64
	Currency    string
	Reason      string
	OrderID     *uuid.UUID
	ActorID     *uuid.UUID
	CreatedAt   time.Time
}

type Device struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	Platform   string
	Model      *string
	AppVersion *string
	PublicKey  []byte
	LastSeenAt *time.Time
	RevokedAt  *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Entitlement struct {
	ID             uuid.UUID
	AccountID      uuid.UUID
	PlanID         uuid.UUID
	LockedPriceID  *uuid.UUID
	Status         string
	StartsAt       time.Time
	ExpiresAt      *time.Time
	CycleIndex     int32
	CycleStart     time.Time
	CycleEnd       *time.Time
	BytesLimit     int64
	DeviceLimit    int32
	SpeedLimitMbps *int32
	ResetPolicy    string
	PaidMinor      int64
	Version        int32
	EndedAt        *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type EntitlementEvent struct {
	ID            uuid.UUID
	EntitlementID uuid.UUID
	AccountID     uuid.UUID
	Type          string
	OrderID       *uuid.UUID
	ActorID       *uuid.UUID
	Reason        *string
	Diff          []byte
	CreatedAt     time.Time
}

type ExportToken struct {
	AccountID uuid.UUID
	TokenHash string
	TokenEnc  []byte
	RotatedAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type IdempotencyKey struct {
	ID              uuid.UUID
	Key             uuid.UUID
	AccountID       *uuid.UUID
	Route           string
	RequestHash     []byte
	ResponseStatus  *int32
	ResponseHeaders []byte
	ResponseBody    []byte
	ExpiresAt       time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Inbound struct {
	ID         uuid.UUID
	NodeID     uuid.UUID
	Protocol   string
	ListenPort int32
	Settings   []byte
	SecretsEnc []byte
	Version    int64
	Enabled    bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type IngestBatch struct {
	ID        uuid.UUID
	Rows      int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type JobFencing struct {
	Job       string
	Token     int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Kernel struct {
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type KernelProtocol struct {
	Kernel    string
	Protocol  string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type KernelTransport struct {
	Kernel    string
	Transport string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type LocationGroup struct {
	ID          uuid.UUID
	Name        string
	Description *string
	MinTier     *int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Machine struct {
	ID              uuid.UUID
	Name            string
	EnrollTokenHash *string
	EnrollExpiresAt *time.Time
	PskEnc          []byte
	PskPrevEnc      []byte
	EnrolledAt      *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type MfaTotp struct {
	AccountID      uuid.UUID
	SecretEnc      []byte
	RecoveryHashes []string
	LastUsedStep   *int64
	EnabledAt      *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type MfaWebauthn struct {
	ID           uuid.UUID
	AccountID    uuid.UUID
	CredentialID []byte
	PublicKey    []byte
	SignCount    int64
	Name         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Node struct {
	ID                uuid.UUID
	MachineID         *uuid.UUID
	Name              string
	RegionCode        string
	PublicHost        string
	Status            string
	TrafficMultiplier pgtype.Numeric
	SpeedLimitMbps    *int32
	EnrollTokenHash   *string
	EnrollExpiresAt   *time.Time
	PskEnc            []byte
	PskPrevEnc        []byte
	KernelType        string
	AllowExperimental bool
	Capabilities      []byte
	AgentVersion      *string
	ConfigVersion     int64
	LastReportSeq     int64
	LastSeenAt        *time.Time
	Sort              int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type NodeGroupMember struct {
	NodeID    uuid.UUID
	GroupID   uuid.UUID
	CreatedAt time.Time
}

type NodeRoute struct {
	ID        uuid.UUID
	NodeID    *uuid.UUID
	GroupID   *uuid.UUID
	Rules     []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type NotificationOutbox struct {
	ID                 uuid.UUID
	AccountID          *uuid.UUID
	Channel            string
	Template           string
	Locale             string
	Variables          []byte
	SecretVariablesEnc []byte
	Attempts           int32
	NextAttemptAt      time.Time
	RetryUntil         time.Time
	SentAt             *time.Time
	FailedAt           *time.Time
	LastError          *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type NotificationPreference struct {
	AccountID uuid.UUID
	Category  string
	Channel   string
	IsEnabled bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type NotificationTemplate struct {
	ID        uuid.UUID
	Template  string
	Locale    string
	Channel   string
	Subject   *string
	Body      string
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Order struct {
	ID                    uuid.UUID
	Number                string
	AccountID             uuid.UUID
	Type                  string
	QuoteID               uuid.UUID
	PriceID               *uuid.UUID
	AddonPriceID          *uuid.UUID
	AmountDueMinor        int64
	CreditUsedMinor       int64
	Currency              string
	Status                string
	Provider              *string
	ProviderTxnID         *string
	PayerRefHash          *string
	PaymentPayload        []byte
	RefundedMinor         int64
	RefundedOriginalMinor int64
	CreatedWhileActive    bool
	ExpiresAt             time.Time
	PaidAt                *time.Time
	FulfilledAt           *time.Time
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Outbox struct {
	ID            uuid.UUID
	Topic         string
	Payload       []byte
	SchemaVersion int32
	PublishedAt   *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type PaymentNotification struct {
	ID          uuid.UUID
	Provider    string
	OrderID     *uuid.UUID
	OutTradeNo  *string
	TradeNo     *string
	TradeStatus *string
	TotalAmount *string
	IsVerified  bool
	Result      string
	Raw         []byte
	ReceivedAt  time.Time
	CreatedAt   time.Time
}

type PaymentProvider struct {
	ID         string
	Enabled    bool
	Config     []byte
	SecretsEnc []byte
	UpdatedBy  *uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Plan struct {
	ID               uuid.UUID
	Name             string
	Description      *string
	Tier             int32
	Kind             string
	BytesPerCycle    int64
	DeviceLimit      int32
	SpeedLimitMbps   *int32
	ResetPolicy      string
	Status           string
	AllowLegacyRenew bool
	Sort             int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type PlanGroup struct {
	PlanID    uuid.UUID
	GroupID   uuid.UUID
	CreatedAt time.Time
}

type PlanPrice struct {
	ID          uuid.UUID
	PlanID      uuid.UUID
	Period      string
	PeriodDays  *int32
	AmountMinor int64
	Currency    string
	OnSale      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProxyCredential struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	DeviceID  *uuid.UUID
	SecretEnc []byte
	RevokedAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Quote struct {
	ID                 uuid.UUID
	AccountID          uuid.UUID
	OrderType          string
	PriceID            *uuid.UUID
	AddonPriceID       *uuid.UUID
	EntitlementID      *uuid.UUID
	EntitlementVersion *int32
	Breakdown          []byte
	AmountDueMinor     int64
	Currency           string
	CouponID           *uuid.UUID
	ExpiresAt          time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type RedeemCode struct {
	ID          uuid.UUID
	CodeHash    string
	Kind        string
	AmountMinor *int64
	Currency    *string
	PriceID     *uuid.UUID
	MaxUses     int32
	UsedCount   int32
	ExpiresAt   *time.Time
	Batch       *string
	DisabledAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RedeemRedemption struct {
	ID             uuid.UUID
	RedeemCodeID   uuid.UUID
	AccountID      uuid.UUID
	CreditLedgerID *uuid.UUID
	EntitlementID  *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ReferralEarning struct {
	ID          uuid.UUID
	ReferrerID  uuid.UUID
	RefereeID   uuid.UUID
	OrderID     uuid.UUID
	AmountMinor int64
	Currency    string
	Status      string
	ReleaseAt   time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Refund struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	AddonID        *uuid.UUID
	AmountMinor    int64
	Destination    string
	Status         string
	ProviderResult []byte
	ActorID        uuid.UUID
	Reason         string
	CompletedAt    *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Role struct {
	Name        string
	Permissions []string
	IsBuiltin   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	ID               uuid.UUID
	AccountID        uuid.UUID
	DeviceID         *uuid.UUID
	Audience         string
	RefreshTokenHash string
	ParentID         *uuid.UUID
	UserAgent        *string
	IpPrefix         *string
	ExpiresAt        time.Time
	UsedAt           *time.Time
	RevokedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Setting struct {
	Key       string
	Value     []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type StaffInvitation struct {
	ID         uuid.UUID
	Email      string
	Role       string
	TokenHash  string
	InviterID  uuid.UUID
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	AccountID  *uuid.UUID
	RevokedAt  *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type SupportAttachment struct {
	ID          uuid.UUID
	UploaderID  uuid.UUID
	MessageID   *uuid.UUID
	ContentType string
	SizeBytes   int64
	Sha256      []byte
	StorageKey  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SupportMessage struct {
	ID        uuid.UUID
	TicketID  uuid.UUID
	AuthorID  uuid.UUID
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SupportTicket struct {
	ID              uuid.UUID
	Number          string
	AccountID       uuid.UUID
	Subject         string
	Category        string
	Status          string
	AssigneeID      *uuid.UUID
	StatusChangedAt time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TrafficDaily struct {
	Day       pgtype.Date
	AccountID uuid.UUID
	NodeID    uuid.UUID
	BytesUp   int64
	BytesDown int64
	RawUp     int64
	RawDown   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TrafficHourly struct {
	Hour      time.Time
	AccountID uuid.UUID
	NodeID    uuid.UUID
	BytesUp   int64
	BytesDown int64
	RawUp     int64
	RawDown   int64
	CreatedAt time.Time
}

type TrafficHourlyDefault struct {
	Hour      time.Time
	AccountID uuid.UUID
	NodeID    uuid.UUID
	BytesUp   int64
	BytesDown int64
	RawUp     int64
	RawDown   int64
	CreatedAt time.Time
}

type UsageCycle struct {
	EntitlementID uuid.UUID
	CycleIndex    int32
	AccountID     uuid.UUID
	BytesUp       int64
	BytesDown     int64
	StartedAt     time.Time
	ClosedAt      *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type VerificationCode struct {
	ID         uuid.UUID
	AccountID  *uuid.UUID
	Purpose    string
	CodeHash   string
	Attempts   int32
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
