// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimDueNotifications = `-- name: ClaimDueNotifications :many
SELECT n.id, n.channel, n.template, n.locale, n.variables, n.secret_variables_enc, n.attempts, n.retry_until,
       a.email
FROM notification_outbox n
JOIN accounts a ON a.id = n.account_id
WHERE n.sent_at IS NULL AND n.failed_at IS NULL AND n.next_attempt_at <= $1
ORDER BY n.next_attempt_at
LIMIT $2
FOR UPDATE OF n SKIP LOCKED
`

type ClaimDueNotificationsParams struct {
	Now     time.Time
	MaxRows int32
}

type ClaimDueNotificationsRow struct {
	ID                 uuid.UUID
	Channel            string
	Template           string
	Locale             string
	Variables          []byte
	SecretVariablesEnc []byte
	Attempts           int32
	RetryUntil         time.Time
	Email              string
}

// 取出到期的消息并锁定；多个 worker 并行时各取不同的行。收件地址在投递时从账号读取（CONV-29）。
func (q *Queries) ClaimDueNotifications(ctx context.Context, arg ClaimDueNotificationsParams) ([]ClaimDueNotificationsRow, error) {
	rows, err := q.db.Query(ctx, claimDueNotifications, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueNotificationsRow
	for rows.Next() {
		var i ClaimDueNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.Template,
			&i.Locale,
			&i.Variables,
			&i.SecretVariablesEnc,
			&i.Attempts,
			&i.RetryUntil,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueNotification = `-- name: EnqueueNotification :exec

INSERT INTO notification_outbox (account_id, channel, template, locale, variables, secret_variables_enc, next_attempt_at, retry_until)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
`

type EnqueueNotificationParams struct {
	AccountID          *uuid.UUID
	Channel            string
	Template           string
	Locale             string
	Variables          []byte
	SecretVariablesEnc []byte
	NextAttemptAt      time.Time
	RetryUntil         time.Time
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// 外发通知队列（spec/13 OPS-02，CONV-31）。
func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error {
	_, err := q.db.Exec(ctx, enqueueNotification,
		arg.AccountID,
		arg.Channel,
		arg.Template,
		arg.Locale,
		arg.Variables,
		arg.SecretVariablesEnc,
		arg.NextAttemptAt,
		arg.RetryUntil,
	)
	return err
}

const getNotificationTemplate = `-- name: GetNotificationTemplate :one
SELECT subject, body FROM notification_templates
WHERE template = $1 AND locale = $2 AND channel = $3
`

type GetNotificationTemplateParams struct {
	Template string
	Locale   string
	Channel  string
}

type GetNotificationTemplateRow struct {
	Subject *string
	Body    string
}

func (q *Queries) GetNotificationTemplate(ctx context.Context, arg GetNotificationTemplateParams) (GetNotificationTemplateRow, error) {
	row := q.db.QueryRow(ctx, getNotificationTemplate, arg.Template, arg.Locale, arg.Channel)
	var i GetNotificationTemplateRow
	err := row.Scan(&i.Subject, &i.Body)
	return i, err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notification_outbox
SET failed_at = $1, attempts = attempts + 1, secret_variables_enc = NULL, last_error = $2
WHERE id = $3
`

type MarkNotificationFailedParams struct {
	Now       *time.Time
	LastError *string
	ID        uuid.UUID
}

// 最终失败：清除秘密变量（CONV-31）。
func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.Now, arg.LastError, arg.ID)
	return err
}

const markNotificationRetry = `-- name: MarkNotificationRetry :exec
UPDATE notification_outbox
SET attempts = attempts + 1, next_attempt_at = $1, last_error = $2
WHERE id = $3
`

type MarkNotificationRetryParams struct {
	NextAttemptAt time.Time
	LastError     *string
	ID            uuid.UUID
}

func (q *Queries) MarkNotificationRetry(ctx context.Context, arg MarkNotificationRetryParams) error {
	_, err := q.db.Exec(ctx, markNotificationRetry, arg.NextAttemptAt, arg.LastError, arg.ID)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notification_outbox
SET sent_at = $1, attempts = attempts + 1, secret_variables_enc = NULL, last_error = NULL
WHERE id = $2
`

type MarkNotificationSentParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) error {
	_, err := q.db.Exec(ctx, markNotificationSent, arg.Now, arg.ID)
	return err
}
