// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reasons.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clearAccountReasonTexts = `-- name: ClearAccountReasonTexts :execrows

UPDATE reason_texts SET body = '' WHERE account_id = $1::uuid AND body <> ''
`

// SPDX-License-Identifier: AGPL-3.0-or-later
// 原因文本（CONV-29）。
// 删除账号个人数据时清空其原因文本（spec/10 AUTH-05），行保留以维持只追加表的引用。
func (q *Queries) ClearAccountReasonTexts(ctx context.Context, accountID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearAccountReasonTexts, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
