// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlc

import (
	"context"
	"time"
)

const clearLegacyInvitationRole = `-- name: ClearLegacyInvitationRole :exec
UPDATE staff_invitations SET role = NULL WHERE role = $1
`

// staff_invitations.role 已废弃（spec/03 3.6），但旧行仍以外键引用角色，删除角色前清空。
func (q *Queries) ClearLegacyInvitationRole(ctx context.Context, role *string) error {
	_, err := q.db.Exec(ctx, clearLegacyInvitationRole, role)
	return err
}

const countExistingRoles = `-- name: CountExistingRoles :one
SELECT count(*) FROM roles WHERE name = ANY($1::text[])
`

func (q *Queries) CountExistingRoles(ctx context.Context, names []string) (int64, error) {
	row := q.db.QueryRow(ctx, countExistingRoles, names)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoles = `-- name: CountRoles :one
SELECT count(*) FROM roles
`

func (q *Queries) CountRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE name = $1 AND NOT is_builtin
`

func (q *Queries) DeleteRole(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteRole, name)
	return err
}

const getRole = `-- name: GetRole :one
SELECT r.name, r.description, r.permissions, r.is_builtin,
       (SELECT count(*) FROM account_roles ar WHERE ar.role = r.name)::int AS staff_count,
       r.created_at, r.updated_at
FROM roles r
WHERE r.name = $1
`

type GetRoleRow struct {
	Name        string
	Description *string
	Permissions []string
	IsBuiltin   bool
	StaffCount  int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetRole(ctx context.Context, name string) (GetRoleRow, error) {
	row := q.db.QueryRow(ctx, getRole, name)
	var i GetRoleRow
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsBuiltin,
		&i.StaffCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRole = `-- name: InsertRole :exec
INSERT INTO roles (name, description, permissions) VALUES ($1, $2, $3)
`

type InsertRoleParams struct {
	Name        string
	Description *string
	Permissions []string
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) error {
	_, err := q.db.Exec(ctx, insertRole, arg.Name, arg.Description, arg.Permissions)
	return err
}

const listRoles = `-- name: ListRoles :many

SELECT r.name, r.description, r.permissions, r.is_builtin,
       (SELECT count(*) FROM account_roles ar WHERE ar.role = r.name)::int AS staff_count,
       r.created_at, r.updated_at
FROM roles r
ORDER BY r.is_builtin DESC, r.name
`

type ListRolesRow struct {
	Name        string
	Description *string
	Permissions []string
	IsBuiltin   bool
	StaffCount  int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// 角色（spec/10 AUTH-17、AUTH-22）。内置角色不可修改、不可删除，由应用层保证。
func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.IsBuiltin,
			&i.StaffCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRole = `-- name: LockRole :one
SELECT name, description, permissions, is_builtin, updated_at FROM roles WHERE name = $1 FOR UPDATE
`

type LockRoleRow struct {
	Name        string
	Description *string
	Permissions []string
	IsBuiltin   bool
	UpdatedAt   time.Time
}

func (q *Queries) LockRole(ctx context.Context, name string) (LockRoleRow, error) {
	row := q.db.QueryRow(ctx, lockRole, name)
	var i LockRoleRow
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsBuiltin,
		&i.UpdatedAt,
	)
	return i, err
}

const roleHasPendingInvitation = `-- name: RoleHasPendingInvitation :one
SELECT EXISTS (
  SELECT 1 FROM staff_invitation_roles ir JOIN staff_invitations i ON i.id = ir.staff_invitation_id
  WHERE ir.role = $1 AND i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > $2
)
`

type RoleHasPendingInvitationParams struct {
	Role string
	Now  time.Time
}

// 仍被 pending 邀请引用的角色不能删除（AUTH-22）。
func (q *Queries) RoleHasPendingInvitation(ctx context.Context, arg RoleHasPendingInvitationParams) (bool, error) {
	row := q.db.QueryRow(ctx, roleHasPendingInvitation, arg.Role, arg.Now)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE roles SET description = $1, permissions = $2
WHERE name = $3 AND NOT is_builtin
`

type UpdateRoleParams struct {
	Description *string
	Permissions []string
	Name        string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole, arg.Description, arg.Permissions, arg.Name)
	return err
}
