// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activeDeviceKeyExists = `-- name: ActiveDeviceKeyExists :one
SELECT EXISTS (
  SELECT 1 FROM devices
  WHERE account_id = $1 AND public_key = $2 AND revoked_at IS NULL
)
`

type ActiveDeviceKeyExistsParams struct {
	AccountID uuid.UUID
	PublicKey []byte
}

// 同一账号未吊销的设备公钥不得重复（AUTH-10）。
func (q *Queries) ActiveDeviceKeyExists(ctx context.Context, arg ActiveDeviceKeyExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, activeDeviceKeyExists, arg.AccountID, arg.PublicKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const activeWebDevicesOverLimit = `-- name: ActiveWebDevicesOverLimit :many
SELECT id FROM devices
WHERE account_id = $1 AND platform = 'web' AND revoked_at IS NULL
ORDER BY last_seen_at ASC NULLS FIRST, id ASC
OFFSET $2::int
`

type ActiveWebDevicesOverLimitParams struct {
	AccountID uuid.UUID
	Keep      int32
}

// 每个账号最多保留 50 个未吊销的 web 设备，超出时吊销最早活跃的（AUTH-10）。
func (q *Queries) ActiveWebDevicesOverLimit(ctx context.Context, arg ActiveWebDevicesOverLimitParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, activeWebDevicesOverLimit, arg.AccountID, arg.Keep)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const childSession = `-- name: ChildSession :one
SELECT id, user_agent, ip_prefix FROM sessions WHERE parent_id = $1
`

type ChildSessionRow struct {
	ID        uuid.UUID
	UserAgent *string
	IpPrefix  *string
}

func (q *Queries) ChildSession(ctx context.Context, parentID *uuid.UUID) (ChildSessionRow, error) {
	row := q.db.QueryRow(ctx, childSession, parentID)
	var i ChildSessionRow
	err := row.Scan(&i.ID, &i.UserAgent, &i.IpPrefix)
	return i, err
}

const countActiveDevices = `-- name: CountActiveDevices :one
SELECT count(*) FROM devices
WHERE account_id = $1 AND platform <> 'web' AND revoked_at IS NULL AND id <> $2
`

type CountActiveDevicesParams struct {
	AccountID uuid.UUID
	Exclude   uuid.UUID
}

// 设备上限只统计未吊销的非 web 设备（AUTH-14）。
func (q *Queries) CountActiveDevices(ctx context.Context, arg CountActiveDevicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDevices, arg.AccountID, arg.Exclude)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeviceCredential = `-- name: CreateDeviceCredential :one
INSERT INTO proxy_credentials (account_id, device_id, secret_enc) VALUES ($1, $2, $3)
RETURNING id
`

type CreateDeviceCredentialParams struct {
	AccountID uuid.UUID
	DeviceID  *uuid.UUID
	SecretEnc []byte
}

func (q *Queries) CreateDeviceCredential(ctx context.Context, arg CreateDeviceCredentialParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createDeviceCredential, arg.AccountID, arg.DeviceID, arg.SecretEnc)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const credentialEntitlement = `-- name: CredentialEntitlement :one
SELECT e.status, e.device_limit FROM entitlements e
WHERE e.account_id = $1 AND e.status IN ('active', 'over_quota', 'suspended')
`

type CredentialEntitlementRow struct {
	Status      string
	DeviceLimit int32
}

// 下发凭据所依据的当前权益：只有 active 可以下发（over_quota、suspended 不下发，spec/30 CredentialStatus）。
func (q *Queries) CredentialEntitlement(ctx context.Context, accountID uuid.UUID) (CredentialEntitlementRow, error) {
	row := q.db.QueryRow(ctx, credentialEntitlement, accountID)
	var i CredentialEntitlementRow
	err := row.Scan(&i.Status, &i.DeviceLimit)
	return i, err
}

const deviceCredential = `-- name: DeviceCredential :one
SELECT id FROM proxy_credentials WHERE device_id = $1 AND revoked_at IS NULL
`

func (q *Queries) DeviceCredential(ctx context.Context, deviceID *uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deviceCredential, deviceID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deviceForReuse = `-- name: DeviceForReuse :one
SELECT id, platform, public_key FROM devices
WHERE id = $1 AND account_id = $2 AND revoked_at IS NULL
FOR UPDATE
`

type DeviceForReuseParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type DeviceForReuseRow struct {
	ID        uuid.UUID
	Platform  string
	PublicKey []byte
}

func (q *Queries) DeviceForReuse(ctx context.Context, arg DeviceForReuseParams) (DeviceForReuseRow, error) {
	row := q.db.QueryRow(ctx, deviceForReuse, arg.ID, arg.AccountID)
	var i DeviceForReuseRow
	err := row.Scan(&i.ID, &i.Platform, &i.PublicKey)
	return i, err
}

const insertDevice = `-- name: InsertDevice :one
INSERT INTO devices (account_id, platform, model, app_version, public_key, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertDeviceParams struct {
	AccountID  uuid.UUID
	Platform   string
	Model      *string
	AppVersion *string
	PublicKey  []byte
	Now        *time.Time
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertDevice,
		arg.AccountID,
		arg.Platform,
		arg.Model,
		arg.AppVersion,
		arg.PublicKey,
		arg.Now,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, account_id, device_id, audience, refresh_token_hash, parent_id, user_agent, ip_prefix, expires_at, absolute_expires_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10)
`

type InsertSessionParams struct {
	ID                uuid.UUID
	AccountID         uuid.UUID
	DeviceID          *uuid.UUID
	Audience          string
	RefreshTokenHash  string
	ParentID          *uuid.UUID
	UserAgent         *string
	IpPrefix          *string
	ExpiresAt         time.Time
	AbsoluteExpiresAt *time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.AccountID,
		arg.DeviceID,
		arg.Audience,
		arg.RefreshTokenHash,
		arg.ParentID,
		arg.UserAgent,
		arg.IpPrefix,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	return err
}

const lockAccount = `-- name: LockAccount :one
SELECT id FROM accounts WHERE id = $1 FOR UPDATE
`

// 串行化同一账号的设备凭据下发，使设备上限的计数与插入之间不会并发超额（AUTH-14）。
func (q *Queries) LockAccount(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockAccount, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const loginAccount = `-- name: LoginAccount :one

SELECT a.id, a.password_hash, a.status, (t.enabled_at IS NOT NULL)::bool AS totp_enabled
FROM accounts a LEFT JOIN mfa_totp t ON t.account_id = a.id
WHERE lower(a.email) = lower($1::text)
`

type LoginAccountRow struct {
	ID           uuid.UUID
	PasswordHash *string
	Status       string
	TotpEnabled  bool
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// 登录、设备与会话（spec/10 AUTH-06–10、AUTH-13、AUTH-14）。
func (q *Queries) LoginAccount(ctx context.Context, email string) (LoginAccountRow, error) {
	row := q.db.QueryRow(ctx, loginAccount, email)
	var i LoginAccountRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.Status,
		&i.TotpEnabled,
	)
	return i, err
}

const markSessionUsed = `-- name: MarkSessionUsed :exec
UPDATE sessions SET used_at = $1 WHERE id = $2
`

type MarkSessionUsedParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkSessionUsed(ctx context.Context, arg MarkSessionUsedParams) error {
	_, err := q.db.Exec(ctx, markSessionUsed, arg.Now, arg.ID)
	return err
}

const revokeAccountSessions = `-- name: RevokeAccountSessions :many
UPDATE sessions SET revoked_at = $1
WHERE account_id = $2 AND revoked_at IS NULL
RETURNING id
`

type RevokeAccountSessionsParams struct {
	Now       *time.Time
	AccountID uuid.UUID
}

func (q *Queries) RevokeAccountSessions(ctx context.Context, arg RevokeAccountSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeAccountSessions, arg.Now, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :exec
UPDATE devices SET revoked_at = $1 WHERE id = $2 AND revoked_at IS NULL
`

type RevokeDeviceParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeDevice, arg.Now, arg.ID)
	return err
}

const revokeDeviceCredentials = `-- name: RevokeDeviceCredentials :many
UPDATE proxy_credentials SET revoked_at = $1
WHERE device_id = $2 AND revoked_at IS NULL
RETURNING id
`

type RevokeDeviceCredentialsParams struct {
	Now      *time.Time
	DeviceID *uuid.UUID
}

func (q *Queries) RevokeDeviceCredentials(ctx context.Context, arg RevokeDeviceCredentialsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeDeviceCredentials, arg.Now, arg.DeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDeviceSessions = `-- name: RevokeDeviceSessions :many
UPDATE sessions SET revoked_at = $1
WHERE device_id = $2 AND revoked_at IS NULL
RETURNING id
`

type RevokeDeviceSessionsParams struct {
	Now      *time.Time
	DeviceID *uuid.UUID
}

func (q *Queries) RevokeDeviceSessions(ctx context.Context, arg RevokeDeviceSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeDeviceSessions, arg.Now, arg.DeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSessionChain = `-- name: RevokeSessionChain :many
WITH RECURSIVE up AS (
  SELECT id, parent_id FROM sessions WHERE sessions.id = $2
  UNION
  SELECT s.id, s.parent_id FROM sessions s JOIN up ON s.id = up.parent_id
), root AS (
  SELECT id FROM up WHERE parent_id IS NULL
), down AS (
  SELECT id FROM root
  UNION
  SELECT s.id FROM sessions s JOIN down ON s.parent_id = down.id
)
UPDATE sessions SET revoked_at = $1
WHERE sessions.id IN (SELECT id FROM down) AND revoked_at IS NULL
RETURNING sessions.id
`

type RevokeSessionChainParams struct {
	Now *time.Time
	ID  uuid.UUID
}

// 吊销会话所在的整条轮换链（AUTH-07）：先沿 parent_id 找到根，再取根的全部后代。
func (q *Queries) RevokeSessionChain(ctx context.Context, arg RevokeSessionChainParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeSessionChain, arg.Now, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionByRefreshHash = `-- name: SessionByRefreshHash :one
SELECT s.id, s.account_id, s.device_id, s.audience, s.parent_id, s.user_agent, s.ip_prefix, s.expires_at, s.absolute_expires_at,
       s.used_at, s.revoked_at, a.status AS account_status, d.revoked_at AS device_revoked_at
FROM sessions s
JOIN accounts a ON a.id = s.account_id
LEFT JOIN devices d ON d.id = s.device_id
WHERE s.refresh_token_hash = $1
FOR UPDATE OF s
`

type SessionByRefreshHashRow struct {
	ID                uuid.UUID
	AccountID         uuid.UUID
	DeviceID          *uuid.UUID
	Audience          string
	ParentID          *uuid.UUID
	UserAgent         *string
	IpPrefix          *string
	ExpiresAt         time.Time
	AbsoluteExpiresAt *time.Time
	UsedAt            *time.Time
	RevokedAt         *time.Time
	AccountStatus     string
	DeviceRevokedAt   *time.Time
}

func (q *Queries) SessionByRefreshHash(ctx context.Context, refreshTokenHash string) (SessionByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, sessionByRefreshHash, refreshTokenHash)
	var i SessionByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.DeviceID,
		&i.Audience,
		&i.ParentID,
		&i.UserAgent,
		&i.IpPrefix,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.AccountStatus,
		&i.DeviceRevokedAt,
	)
	return i, err
}

const sessionChainRoot = `-- name: SessionChainRoot :one
WITH RECURSIVE up AS (
  SELECT id, parent_id FROM sessions WHERE sessions.id = $1
  UNION
  SELECT s.id, s.parent_id FROM sessions s JOIN up ON s.id = up.parent_id
)
SELECT id FROM up WHERE parent_id IS NULL
`

// 会话所在轮换链的根（AUTH-07）。Mfa-Assertion 绑定会话链，以根会话标识（AUTH-19）。
func (q *Queries) SessionChainRoot(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, sessionChainRoot, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const sessionDescendsFrom = `-- name: SessionDescendsFrom :one
WITH RECURSIVE chain AS (
  SELECT id, parent_id, 0 AS depth FROM sessions WHERE sessions.id = $2
  UNION ALL
  SELECT s.id, s.parent_id, chain.depth + 1 FROM sessions s JOIN chain ON s.id = chain.parent_id WHERE chain.depth < 32
)
SELECT (count(*) > 0)::bool AS descends FROM chain WHERE chain.id = $1::uuid
`

type SessionDescendsFromParams struct {
	Ancestor uuid.UUID
	Current  uuid.UUID
}

// current 是否为 ancestor 本身，或由它经刷新轮换产生（AUTH-11：待确认的 TOTP 密钥绑定会话链）。
// 只向上查 32 代：待确认密钥 10 分钟内有效，期间的轮换远少于此。
func (q *Queries) SessionDescendsFrom(ctx context.Context, arg SessionDescendsFromParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionDescendsFrom, arg.Ancestor, arg.Current)
	var descends bool
	err := row.Scan(&descends)
	return descends, err
}

const sessionDevice = `-- name: SessionDevice :one
SELECT device_id FROM sessions WHERE id = $1 AND account_id = $2
`

type SessionDeviceParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) SessionDevice(ctx context.Context, arg SessionDeviceParams) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, sessionDevice, arg.ID, arg.AccountID)
	var device_id *uuid.UUID
	err := row.Scan(&device_id)
	return device_id, err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET model = $1, app_version = $2, last_seen_at = $3
WHERE id = $4
`

type TouchDeviceParams struct {
	Model      *string
	AppVersion *string
	Now        *time.Time
	ID         uuid.UUID
}

func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.db.Exec(ctx, touchDevice,
		arg.Model,
		arg.AppVersion,
		arg.Now,
		arg.ID,
	)
	return err
}
