// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
)

const getSetting = `-- name: GetSetting :one

SELECT value FROM settings WHERE key = $1
`

// SPDX-License-Identifier: AGPL-3.0-or-later
// 设置项（spec/03 settings，键名见 spec/03 3.6 与管理接口）。
func (q *Queries) GetSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}
