// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
	"time"
)

const bumpConfigIssuedAt = `-- name: BumpConfigIssuedAt :one
INSERT INTO settings (key, value)
VALUES ('config_issued_at', to_jsonb(to_char(date_trunc('second', $1::timestamptz) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')))
ON CONFLICT (key) DO UPDATE SET value = to_jsonb(to_char(
  GREATEST(
    date_trunc('second', $1::timestamptz),
    CASE
      WHEN jsonb_typeof(settings.value) = 'string' AND (settings.value #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$'
        THEN (settings.value #>> '{}')::timestamptz
      ELSE ('invalid config_issued_at' || left(settings.value::text, 0))::timestamptz
    END + interval '1 second'
  ) AT TIME ZONE 'UTC',
  'YYYY-MM-DD"T"HH24:MI:SS"Z"'))
RETURNING (value #>> '{}')::text AS issued_at
`

// 更新 config_issued_at（spec/30 API-11）：写入 max(当前时刻, 上一次的值 + 1 秒)，秒精度 RFC 3339 UTC，严格递增；
// 键缺失时写入当前时刻。单条语句，ON CONFLICT DO UPDATE 锁住该行直到事务结束，并发修改不会得到相同的值。
// now 由调用方从注入的时钟取得（CONV-04、CONV-27）；在修改 features、registration_policy、min_version 有效值的
// 同一事务中调用。
// 已存的值必须是 JSON 字符串 YYYY-MM-DDTHH:MM:SSZ，否则转换失败、修改随之失败（fail-closed，只有直接改库才会出现）：
// timestamptz 的输入还接受 'now'、'epoch'、'infinity' 与不带时区的字符串，JSON null 会使 GREATEST 忽略上一次的值，
// 因此先按格式校验。ELSE 分支拼接行内的值（长度为 0），避免常量表达式在计划阶段被提前求值而无条件报错。
func (q *Queries) BumpConfigIssuedAt(ctx context.Context, now time.Time) (string, error) {
	row := q.db.QueryRow(ctx, bumpConfigIssuedAt, now)
	var issued_at string
	err := row.Scan(&issued_at)
	return issued_at, err
}

const getSetting = `-- name: GetSetting :one

SELECT value FROM settings WHERE key = $1
`

// SPDX-License-Identifier: AGPL-3.0-or-later
// 设置项（spec/03 settings，键名见 spec/03 3.6 与管理接口）。
func (q *Queries) GetSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const initSetting = `-- name: InitSetting :exec
INSERT INTO settings (key, value) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING
`

type InitSettingParams struct {
	Key   string
	Value []byte
}

// 写入尚不存在的设置项；已存在时不变（并发时先写入者生效）。
func (q *Queries) InitSetting(ctx context.Context, arg InitSettingParams) error {
	_, err := q.db.Exec(ctx, initSetting, arg.Key, arg.Value)
	return err
}
