// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const accountRoles = `-- name: AccountRoles :many
SELECT role FROM account_roles WHERE account_id = $1 ORDER BY role
`

func (q *Queries) AccountRoles(ctx context.Context, accountID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, accountRoles, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAccountRoles = `-- name: DeleteAccountRoles :exec
DELETE FROM account_roles WHERE account_id = $1
`

func (q *Queries) DeleteAccountRoles(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountRoles, accountID)
	return err
}

const deleteWebauthn = `-- name: DeleteWebauthn :exec
DELETE FROM mfa_webauthn WHERE account_id = $1
`

func (q *Queries) DeleteWebauthn(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebauthn, accountID)
	return err
}

const getStaff = `-- name: GetStaff :one
SELECT a.id, a.email,
       array_agg(ar.role ORDER BY ar.role)::text[] AS roles,
       EXISTS (SELECT 1 FROM mfa_totp t WHERE t.account_id = a.id)::boolean AS has_totp,
       EXISTS (SELECT 1 FROM mfa_webauthn w WHERE w.account_id = a.id)::boolean AS has_passkey,
       min(ar.created_at)::timestamptz AS created_at
FROM accounts a
JOIN account_roles ar ON ar.account_id = a.id
WHERE a.id = $1
GROUP BY a.id
`

type GetStaffRow struct {
	ID         uuid.UUID
	Email      string
	Roles      []string
	HasTotp    bool
	HasPasskey bool
	CreatedAt  time.Time
}

func (q *Queries) GetStaff(ctx context.Context, id uuid.UUID) (GetStaffRow, error) {
	row := q.db.QueryRow(ctx, getStaff, id)
	var i GetStaffRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Roles,
		&i.HasTotp,
		&i.HasPasskey,
		&i.CreatedAt,
	)
	return i, err
}

const listStaff = `-- name: ListStaff :many
SELECT a.id, a.email,
       array_agg(ar.role ORDER BY ar.role)::text[] AS roles,
       EXISTS (SELECT 1 FROM mfa_totp t WHERE t.account_id = a.id)::boolean AS has_totp,
       EXISTS (SELECT 1 FROM mfa_webauthn w WHERE w.account_id = a.id)::boolean AS has_passkey,
       min(ar.created_at)::timestamptz AS created_at
FROM accounts a
JOIN account_roles ar ON ar.account_id = a.id
WHERE ($1::text IS NULL
       OR EXISTS (SELECT 1 FROM account_roles x WHERE x.account_id = a.id AND x.role = $1::text))
  AND ($2::uuid IS NULL OR a.id > $2::uuid)
GROUP BY a.id
ORDER BY a.id
LIMIT $3
`

type ListStaffParams struct {
	Role    *string
	After   *uuid.UUID
	MaxRows int32
}

type ListStaffRow struct {
	ID         uuid.UUID
	Email      string
	Roles      []string
	HasTotp    bool
	HasPasskey bool
	CreatedAt  time.Time
}

// 按账号 ID 分页（CONV-11）。最近登录时间见 StaffLastLogins。
func (q *Queries) ListStaff(ctx context.Context, arg ListStaffParams) ([]ListStaffRow, error) {
	rows, err := q.db.Query(ctx, listStaff, arg.Role, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffRow
	for rows.Next() {
		var i ListStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Roles,
			&i.HasTotp,
			&i.HasPasskey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleHolders = `-- name: RoleHolders :many
SELECT account_id FROM account_roles WHERE role = $1
`

func (q *Queries) RoleHolders(ctx context.Context, role string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, roleHolders, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var account_id uuid.UUID
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staffLastLogins = `-- name: StaffLastLogins :many
SELECT account_id, max(created_at)::timestamptz AS last_login_at
FROM sessions
WHERE account_id = ANY($1::uuid[]) AND audience = 'console' AND parent_id IS NULL
GROUP BY account_id
`

type StaffLastLoginsRow struct {
	AccountID   uuid.UUID
	LastLoginAt time.Time
}

// 最近登录时间：管理会话链的根会话的建立时间，只用于展示（CONV-27）。从未登录的账号没有行。
func (q *Queries) StaffLastLogins(ctx context.Context, accountIds []uuid.UUID) ([]StaffLastLoginsRow, error) {
	rows, err := q.db.Query(ctx, staffLastLogins, accountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffLastLoginsRow
	for rows.Next() {
		var i StaffLastLoginsRow
		if err := rows.Scan(&i.AccountID, &i.LastLoginAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staffPrincipal = `-- name: StaffPrincipal :one

SELECT a.status, a.email,
       EXISTS (SELECT 1 FROM mfa_totp t WHERE t.account_id = a.id)::boolean AS has_totp,
       EXISTS (SELECT 1 FROM mfa_webauthn w WHERE w.account_id = a.id)::boolean AS has_passkey,
       COALESCE((SELECT array_agg(ar.role ORDER BY ar.role) FROM account_roles ar WHERE ar.account_id = a.id), '{}')::text[] AS roles,
       COALESCE((SELECT array_agg(DISTINCT p ORDER BY p)
                 FROM account_roles ar JOIN roles r ON r.name = ar.role, unnest(r.permissions) AS p
                 WHERE ar.account_id = a.id), '{}')::text[] AS permissions
FROM accounts a
WHERE a.id = $1
`

type StaffPrincipalRow struct {
	Status      string
	Email       string
	HasTotp     bool
	HasPasskey  bool
	Roles       []string
	Permissions []string
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// 管理员（spec/10 AUTH-12、AUTH-21、AUTH-22）。管理员即持有至少一个角色的账号。
// 管理接口每个请求读取一次（AUTH-12、AUTH-17）：账号状态、是否启用 TOTP、角色与展开后的权限。
// 角色与二次验证的变化因此立即生效，不依赖访问令牌过期。
func (q *Queries) StaffPrincipal(ctx context.Context, id uuid.UUID) (StaffPrincipalRow, error) {
	row := q.db.QueryRow(ctx, staffPrincipal, id)
	var i StaffPrincipalRow
	err := row.Scan(
		&i.Status,
		&i.Email,
		&i.HasTotp,
		&i.HasPasskey,
		&i.Roles,
		&i.Permissions,
	)
	return i, err
}
